# Feature file for Section 6.2: Continuous Effects
# Reference: Flesh and Blood Comprehensive Rules Section 6.2
#
# Rule 6.2.1: A continuous effect modifies the state and properties of objects,
# and/or the rules of the game. Continuous effects either have a lasting influence
# effect on the game state, and continue for their specified duration, or for as
# long as their source ability is functional.
#
# Rule 6.2.2: A layer-continuous effect is a continuous effect generated by the
# resolution of a layer. Layer continuous effects typically have a specified duration.
#
# Rule 6.2.2a: A layer-continuous effect starts as soon it is generated and ends
# after a specified duration or when it is not longer applicable. A specified duration
# is fixed at the time the effect is generated and does not change once generated.
# If no duration is explicitly specified by the effect and the effect is not explicitly
# dependent on a condition, the effect ends at the end of the turn it was generated.
#
# Example (6.2.2a): Stasis Cell: "activated abilities of target equipment can't be
# activated until the end of its controller's next turn." Duration fixed at generation.
# Example (6.2.2a): Chains of Eminence: condition-dependent (while in arena).
# Example (6.2.2a): Tempest Aurora: no explicit duration -> ends at end of current turn.
#
# Rule 6.2.2b: If a layer-continuous effect has variable values (such as X), the
# values of those variables are determined when the continuous effect is generated and
# do not change thereafter. If the effect applies to an object that does not yet exist,
# the variables are determined when the effect first applies to an object.
#
# Example (6.2.2b): Tear Limb from Limb: X is determined at time effect first applies
# to an object, not when it is first generated.
#
# Rule 6.2.2c: If a layer-continuous effect starts to apply to an object, it continues
# to apply to that object even if the properties of that object change.
#
# Example (6.2.2c): Cut Deep gives +4{p} to next dagger attack. If that card later
# becomes a non-dagger via Take Up the Mantle, the effect still applies.
#
# Rule 6.2.2d: If a layer-continuous effect is conditional on being generated, its
# condition is evaluated only once. If the effect is conditional on being applied,
# the condition is still checked continuously.
#
# Rule 6.2.3: A static-continuous effect is a continuous effect generated by a static
# ability. Static-continuous effects never have a specified duration.
#
# Rule 6.2.3a: A static-continuous effect starts as soon as the static ability becomes
# functional and ends when the static ability becomes non-functional.
#
# Rule 6.2.3b: If a static-continuous effect has variable values (such as X), the
# value of those variables are determined based on the current game state and are
# updated if the game state changes.
#
# Rule 6.2.3c: A static-continuous effect only applies to an object while it has the
# properties described by the effect - if the properties of an object change, the
# static effect may no longer apply to that object.
#
# Rule 6.2.3d: If a static-continuous effect is conditional on being generated, its
# condition is evaluated at all times. The effect is generated when the condition is
# met and ceases to exist when the condition is not met.
#
# Example (6.2.3d): Luminaris: "If there is a yellow card in your pitch zone, Illusionist
# attacks you control have go again." Condition evaluated continuously.
#
# Rule 6.2.4: If a continuous effect would only apply to a future object that is yet to
# exist, it starts to apply to the next object that meets the specification of the effect.
#
# Example (6.2.4): Come to Fight: "The next attack action card you play this turn gains
# +3{p}."
#
# Rule 6.2.5: The first time a continuous effect applies to an object, or when a
# continuous effect changes how it modifies an object, it applies as an event which
# can be modified by replacement effects and trigger triggered effects.
#
# Rule 6.2.5a: If two or more effects would apply to an object at the same time, they
# are applied in the order determined by staging.

Feature: Section 6.2 - Continuous Effects
    As a game engine
    I need to correctly implement continuous effects
    So that ongoing game state modifications are tracked with proper duration and scope

    # ===== Rule 6.2.1: Continuous effects modify state/properties/rules =====

    # Test for Rule 6.2.1 - Continuous effect modifies object properties
    Scenario: A continuous effect modifies the properties of an object
        Given a game is in progress
        And a player has a continuous effect that grants "+2{p}" to an attack
        When the effect is active
        Then the attack's power property is modified by the continuous effect
        And the modification persists until the effect's duration expires

    # Test for Rule 6.2.1 - Continuous effect modifies rules of the game
    Scenario: A continuous effect modifies the rules of the game
        Given a game is in progress
        And a continuous effect that prevents pitching cards is active
        When a player attempts to pitch a card
        Then the pitch action is prevented by the continuous rule modification

    # ===== Rule 6.2.2: Layer-continuous effects =====

    # Test for Rule 6.2.2 - Layer-continuous effect generated by layer resolution
    Scenario: A layer-continuous effect is generated when a layer resolves
        Given a game is in progress
        And a player resolves a card with a lasting power bonus effect
        When the layer resolves
        Then a layer-continuous effect is created in the game state
        And the effect modifies the targeted object's properties

    # ===== Rule 6.2.2a: Duration fixed at generation time =====

    # Test for Rule 6.2.2a - Effect starts immediately when generated
    Scenario: A layer-continuous effect starts immediately upon generation
        Given a game is in progress
        And a player plays a card that creates a layer-continuous effect
        When the layer resolves and the effect is generated
        Then the continuous effect is active immediately
        And the effect modifies the targeted object right away

    # Test for Rule 6.2.2a - Specified duration is fixed at generation and does not change
    Scenario: The duration of a layer-continuous effect is fixed at generation time
        Given a game is in progress
        And a player generates a layer-continuous effect with duration "until end of controller's next turn"
        When the controller of the affected object changes
        Then the duration of the effect remains "until end of the original controller's next turn"
        And the duration does not track the new controller's turn

    # Test for Rule 6.2.2a - No explicit duration means effect ends at end of current turn
    Scenario: A layer-continuous effect with no explicit duration ends at end of turn
        Given a game is in progress
        And a player generates a layer-continuous effect with no explicit duration or condition
        When the current turn ends
        Then the layer-continuous effect is no longer active
        And the effect no longer modifies any objects

    # Test for Rule 6.2.2a - Condition-dependent effect ends when condition is no longer met
    Scenario: A condition-dependent layer-continuous effect ends when its condition is no longer met
        Given a game is in progress
        And a player has a permanent with a condition-dependent continuous effect in the arena
        When the permanent leaves the arena
        Then the condition-dependent continuous effect ends
        And the effect is no longer active

    # ===== Rule 6.2.2b: Variable values fixed at generation (or first application) =====

    # Test for Rule 6.2.2b - Variable values fixed when effect is generated
    Scenario: A layer-continuous effect with variable X fixes X at generation time
        Given a game is in progress
        And a player generates a layer-continuous effect with a variable power bonus "X"
        And the value of X is "3" when the effect is generated
        When the game state changes so that X would be "5"
        Then the continuous effect still grants "+3{p}" based on the original X value
        And the effect does not update to use the new value of X

    # Test for Rule 6.2.2b - X determined when effect first applies to object that didn't exist
    Scenario: Variable X in a layer-continuous effect is fixed when the effect first applies to a new object
        Given a game is in progress
        And a player generates a layer-continuous effect that applies to the next attack played with "+X{p} where X is its base power"
        And the next attack played has base power "4"
        When the layer-continuous effect first applies to that attack
        Then the effect grants "+4{p}" based on the attack's base power at time of application
        And the bonus does not change if the attack's power changes later

    # ===== Rule 6.2.2c: Effect persists even if object's properties change =====

    # Test for Rule 6.2.2c - Effect keeps applying after object's type changes
    Scenario: A layer-continuous effect continues to apply after the target's properties change
        Given a game is in progress
        And a player generates a layer-continuous effect targeting "the next dagger attack" with "+4{p}"
        And the effect starts to apply to a card that is a dagger attack
        When the card's type is changed to "non-dagger" by another effect
        Then the "+4{p}" layer-continuous effect still applies to the card
        And the power bonus remains active despite the type change

    # ===== Rule 6.2.2d: Conditional generation vs conditional application =====

    # Test for Rule 6.2.2d - Generation condition evaluated only once
    Scenario: A layer-continuous effect's generation condition is evaluated only once
        Given a game is in progress
        And a player has a card with a conditional continuous effect "if you have more life than your opponent, your next attack gets +2{p}"
        And the condition is true when the layer resolves
        When the layer resolves and the effect is generated
        Then the effect is generated because the condition was met at generation time
        And if the player's life later drops below the opponent's life, the effect remains generated

    # Test for Rule 6.2.2d - Application condition is checked continuously
    Scenario: A layer-continuous effect's application condition is checked continuously
        Given a game is in progress
        And a layer-continuous effect that applies conditionally based on an ongoing game state property is active
        When the ongoing condition becomes false
        Then the effect no longer applies to objects until the condition becomes true again

    # ===== Rule 6.2.3: Static-continuous effects =====

    # Test for Rule 6.2.3 - Static-continuous effect from static ability
    Scenario: A static-continuous effect is generated by a static ability
        Given a game is in progress
        And a permanent with a static ability granting "+1{p} to all your attacks" is in the arena
        When an attack card is played by the controlling player
        Then the static-continuous effect applies the "+1{p}" bonus to the attack
        And the effect has no specified duration

    # ===== Rule 6.2.3a: Static effect starts/ends with static ability functional status =====

    # Test for Rule 6.2.3a - Static-continuous effect starts when ability becomes functional
    Scenario: A static-continuous effect starts when its source static ability becomes functional
        Given a game is in progress
        And a permanent with a static ability enters the arena
        When the permanent enters the arena and its static ability becomes functional
        Then the static-continuous effect is immediately active
        And it applies to qualifying objects

    # Test for Rule 6.2.3a - Static-continuous effect ends when ability becomes non-functional
    Scenario: A static-continuous effect ends when its source static ability becomes non-functional
        Given a game is in progress
        And a permanent with a static ability is in the arena generating a continuous effect
        When the permanent leaves the arena and the static ability becomes non-functional
        Then the static-continuous effect is no longer active
        And objects previously modified by the effect lose the modification

    # ===== Rule 6.2.3b: Static effect variable values update with game state =====

    # Test for Rule 6.2.3b - Variable values in static effects update dynamically
    Scenario: Variable values in a static-continuous effect update when game state changes
        Given a game is in progress
        And a static-continuous effect grants "+X{p}" where X is the number of cards in hand
        And the player has "3" cards in hand
        When the player draws a card and now has "4" cards in hand
        Then the static-continuous effect now grants "+4{p}"
        And the variable value has updated to reflect the current game state

    # ===== Rule 6.2.3c: Static effect only applies while object has required properties =====

    # Test for Rule 6.2.3c - Static effect stops applying if object's properties change
    Scenario: A static-continuous effect stops applying when the target loses qualifying properties
        Given a game is in progress
        And a static-continuous effect applies to all "Illusionist attacks" granting go again
        And a card is an "Illusionist attack" currently benefiting from the effect
        When the card's type changes so it is no longer an "Illusionist attack"
        Then the static-continuous effect no longer applies to that card
        And the card no longer benefits from go again

    # ===== Rule 6.2.3d: Static effect condition evaluated continuously =====

    # Test for Rule 6.2.3d - Conditional static effect activates when condition becomes true
    Scenario: A conditional static-continuous effect activates when its condition becomes true
        Given a game is in progress
        And a permanent has a conditional static ability "if there is a yellow card in pitch zone, Illusionist attacks have go again"
        And the player's pitch zone has no yellow cards
        When the player pitches a yellow card to the pitch zone
        Then the conditional static-continuous effect becomes active
        And Illusionist attacks controlled by that player now have go again

    # Test for Rule 6.2.3d - Conditional static effect deactivates when condition becomes false
    Scenario: A conditional static-continuous effect deactivates when its condition becomes false
        Given a game is in progress
        And a conditional static-continuous effect is currently active because its condition is met
        When the condition becomes false
        Then the conditional static-continuous effect ceases to exist
        And the modification it applied is removed from all affected objects

    # ===== Rule 6.2.4: Effect applies to next future qualifying object =====

    # Test for Rule 6.2.4 - Continuous effect waits for the next qualifying object
    Scenario: A continuous effect that targets a future object applies to the next qualifying object
        Given a game is in progress
        And a player generates a continuous effect "the next attack action card you play this turn gets +3{p}"
        When the player plays an attack action card
        Then the continuous effect applies its "+3{p}" bonus to that attack
        And the effect is consumed and does not apply to subsequent attacks

    # Test for Rule 6.2.4 - Effect does not apply to objects that existed before generation
    Scenario: A continuous effect for a future object does not apply to objects that already exist
        Given a game is in progress
        And an attack action card is already on the combat chain
        And a player generates a continuous effect "the next attack action card you play this turn gets +3{p}"
        When the player does not play another attack action card
        Then the existing attack action card on the combat chain is not affected
        And the effect waits for a new qualifying object

    # ===== Rule 6.2.5: Application is an event that can be modified =====

    # Test for Rule 6.2.5 - First application of continuous effect is an event
    Scenario: The first application of a continuous effect to an object is an event
        Given a game is in progress
        And a continuous effect is waiting to apply to the next qualifying attack
        When the continuous effect first applies to an attack
        Then this application is processed as an event in the game
        And the event can trigger triggered effects and be modified by replacement effects

    # Test for Rule 6.2.5 - Change in how effect modifies an object is also an event
    Scenario: A change in how a continuous effect modifies an object is treated as an event
        Given a game is in progress
        And a continuous effect is currently applying "+2{p}" to an attack
        When a replacement effect changes the application to "+5{p}" instead
        Then the change in modification is processed as an event
        And the attack gains "+5{p}" from the modified application

    # ===== Rule 6.2.5a: Multiple simultaneous effects applied in staging order =====

    # Test for Rule 6.2.5a - Two simultaneous effects applied in staging order
    Scenario: Two continuous effects applying to an object simultaneously are applied in staging order
        Given a game is in progress
        And two continuous effects would both apply to an attack at the same time
        When the effects are applied to the attack
        Then they are applied in the order determined by the staging system
        And each application is a separate event
