# Feature file for Section 2.8: Pitch
# Reference: Flesh and Blood Comprehensive Rules Section 2.8
#
# 2.8.1 Pitch is a property of a card, which represents the assets a player gains
#        when they pitch the card. The pitch value of the card is the number of assets
#        gained when pitched and it determines the object's uniqueness (along with the
#        name property).
#        Cross-references: [1.14.3], [1.3.4]
#
# 2.8.2 The printed pitch of a card is expressed visually as one, two, or three
#        socketed {r} or {c} symbols, typically located in the top left corner of a
#        card, where the types of symbols dictate what asset is generated when pitched
#        and the number of symbols dictates the printed pitch value. The printed pitch
#        value defines the base pitch value of a card. If a card does not have a
#        printed pitch value, it does not have the pitch property.
#
# 2.8.3 The pitch of an object can be modified. The term "pitch" refers to the
#        modified pitch value of an object.
#
# 2.8.4 The visual expression of {r} or {c} symbols and the numerical expression of
#        pitch are functionally identical.
#        Example: The text "Search your deck for a card with pitch value 1," is
#        considered to be the same as the text "Search your deck for a card with
#        pitch value {r}."

Feature: Section 2.8 - Pitch
    As a game engine
    I need to correctly implement pitch rules
    So that card pitch values determine assets gained, uniqueness, and are correctly modified

    # Rule 2.8.1 - Pitch is a property representing assets gained when pitched
    Scenario: Pitch is a property of a card
        Given a pitch card is created with a printed pitch of 2
        When the engine checks the pitch property of the pitch 2 card
        Then the pitch 2 card should have the pitch property
        And the pitch of the pitch 2 card should be 2

    # Rule 2.8.1 - Pitch value represents the number of assets gained when pitched
    Scenario: Pitch value represents assets gained when pitching
        Given a pitch card is created with a printed pitch of 3
        When the engine pitches the pitch 3 card to gain assets
        Then the assets gained from pitching the pitch 3 card should be 3

    # Rule 2.8.1 - Pitch determines uniqueness together with name
    Scenario: Pitch value contributes to card uniqueness with name
        Given a pitch card named "Sink Below" with pitch value 1 is created
        And another pitch card named "Sink Below" with pitch value 3 is created
        When the engine checks if the two Sink Below cards are distinct
        Then the two Sink Below cards should be distinct due to different pitch values

    # Rule 2.8.1 - Cards with same name and pitch are not distinct
    Scenario: Cards with same name and same pitch value are not distinct
        Given a pitch card named "Pummel" with pitch value 1 is created
        And another pitch card named "Pummel" with pitch value 1 is also created
        When the engine checks if the two Pummel cards are distinct
        Then the two Pummel cards should not be distinct

    # Rule 2.8.2 - Printed pitch expressed as resource symbols, one symbol = pitch 1
    Scenario: Card with one resource symbol has pitch value 1
        Given a pitch card is created with 1 resource symbol in the pitch area
        When the engine checks the printed pitch of the 1-resource-symbol card
        Then the printed pitch of the 1-resource-symbol card should be 1

    # Rule 2.8.2 - Two resource symbols = pitch value 2
    Scenario: Card with two resource symbols has pitch value 2
        Given a pitch card is created with 2 resource symbols in the pitch area
        When the engine checks the printed pitch of the 2-resource-symbol card
        Then the printed pitch of the 2-resource-symbol card should be 2

    # Rule 2.8.2 - Three resource symbols = pitch value 3
    Scenario: Card with three resource symbols has pitch value 3
        Given a pitch card is created with 3 resource symbols in the pitch area
        When the engine checks the printed pitch of the 3-resource-symbol card
        Then the printed pitch of the 3-resource-symbol card should be 3

    # Rule 2.8.2 - Symbol type dictates what asset is generated when pitched
    Scenario: Resource symbols generate resource points when pitched
        Given a pitch card is created with 2 resource symbols for resource asset type
        When the engine determines the asset type generated by the resource-symbol pitch card
        Then the resource-symbol pitch card should generate resource points when pitched

    # Rule 2.8.2 - Chi symbols generate chi points when pitched
    Scenario: Chi symbols generate chi points when pitched
        Given a pitch card is created with 1 chi symbol for chi asset type
        When the engine determines the asset type generated by the chi-symbol pitch card
        Then the chi-symbol pitch card should generate chi points when pitched

    # Rule 2.8.2 - Printed pitch defines base pitch value
    Scenario: Printed pitch defines the base pitch value of a card
        Given a pitch card is created with a printed pitch of 2
        When the engine checks the base pitch of the base-pitch-2 card
        Then the base pitch of the base-pitch-2 card should be 2

    # Rule 2.8.2 - Card without printed pitch lacks pitch property
    Scenario: Card without a printed pitch lacks the pitch property
        Given a pitch card is created with no printed pitch
        When the engine checks the pitch property of the no-pitch card
        Then the no-pitch card should not have the pitch property

    # Rule 2.8.3 - Pitch of an object can be modified
    Scenario: Pitch of an object can be modified by effects
        Given a pitch card is created with a printed pitch of 1
        And a pitch boost effect of plus 1 is applied to the pitch 1 card
        When the engine checks the modified pitch of the pitch 1 card
        Then the modified pitch of the pitch 1 card should be 2

    # Rule 2.8.3 - "pitch" refers to the modified pitch value
    Scenario: The term pitch refers to the modified pitch value not base pitch
        Given a pitch card is created with a printed pitch of 2
        And a pitch boost effect of plus 1 is applied to the pitch 2 card
        When the engine resolves the term pitch for the pitch 2 card
        Then the resolved pitch of the pitch 2 card should be 3
        And the base pitch of the pitch 2 card should remain 2

    # Rule 2.8.3 - Pitch can be decreased by effects
    Scenario: Pitch of an object can be decreased by effects
        Given a pitch card is created with a printed pitch of 3
        And a pitch reduction effect of minus 1 is applied to the pitch 3 card
        When the engine checks the modified pitch of the pitch 3 card
        Then the modified pitch of the pitch 3 card should be 2

    # Rule 2.8.3 - Pitch cannot go below zero (cross-ref Rule 2.0.3c)
    Scenario: Pitch cannot be reduced below zero
        Given a pitch card is created with a printed pitch of 1
        And a pitch reduction effect of minus 3 is applied to the pitch 1 card
        When the engine checks the modified pitch of the pitch 1 card
        Then the modified pitch of the pitch 1 card should be 0

    # Rule 2.8.4 - Visual symbols and numerical expression are functionally identical
    Scenario: One resource symbol is functionally identical to numeric pitch 1
        Given a pitch card is created with a cost expressed as one resource symbol pitch
        When the engine interprets the resource symbol pitch as numeric
        Then the numeric pitch equivalent should be 1

    # Rule 2.8.4 - Searching by numeric pitch value finds cards with matching resource symbols
    Scenario: Searching by numeric pitch value finds cards with matching resource symbols
        Given a pitch card named "Numeric Pitch 1 Card" is created with a numeric pitch of 1
        And a pitch card named "Symbol Pitch 1 Card" is created with one resource symbol pitch
        When the engine searches for cards with pitch value 1
        Then both "Numeric Pitch 1 Card" and "Symbol Pitch 1 Card" should be found

    # Rule 2.8.2 - Multiple cards each have independent pitch values
    Scenario: Multiple cards each have independent pitch values
        Given a pitch card is created with a printed pitch of 1
        And another pitch card is created with a printed pitch of 3
        When the engine checks both pitch cards
        Then the first pitch card pitch should be 1
        And the second pitch card pitch should be 3
