# Feature file for Section 6.0: General (Effects)
# Reference: Flesh and Blood Comprehensive Rules Section 6.0
#
# Section 6.0 General is an introductory header for Chapter 6: Effects.
# There are no specific numbered rules in section 6.0 itself. Detailed rules are in:
#   - 6.1: Discrete Effects
#   - 6.2: Continuous Effects
#   - 6.3: Continuous Effect Interactions
#   - 6.4: Replacement Effects
#   - 6.5: Replacement Effect Interactions
#   - 6.6: Triggered Effects
#
# Chapter 6 governs how effects work in Flesh and Blood. Effects are produced by
# abilities and change the game state in various ways. Effects are either discrete
# (producing a single event with no duration) or continuous (modifying state/properties
# over a specified duration). Replacement effects intercept events and substitute
# modified versions. Triggered effects respond to specific game events.

Feature: Section 6.0 - Effects General
    As a game engine
    I need to correctly model the chapter 6 concepts of effects
    So that game state changes, continuous modifications, and event replacements work correctly

    # ===== Chapter 6 Introduction: Two main types of effects =====

    # Test for Chapter 6 introduction - Discrete effects have no duration
    Scenario: Discrete effects change game state by producing a single event with no duration
        Given a game is in progress
        When a discrete effect is generated
        Then the effect produces an event that changes the game state
        And after the event completes the effect has no further influence

    # Test for Chapter 6 introduction - Continuous effects have lasting influence
    Scenario: Continuous effects modify state and properties over a duration
        Given a game is in progress
        When a continuous effect is generated
        Then the effect modifies game state for its specified duration
        And the effect continues to apply until its duration ends

    # Test for Chapter 6 introduction - Layer-continuous effects from layer resolution
    Scenario: Layer-continuous effects are generated when a layer resolves on the stack
        Given a game is in progress
        And a layer is on the stack with a continuous effect
        When the layer resolves
        Then a layer-continuous effect is generated
        And the effect has a specified duration

    # Test for Chapter 6 introduction - Static-continuous effects from static abilities
    Scenario: Static-continuous effects are generated by static abilities
        Given a permanent with a static ability is in the arena
        When the game state is evaluated
        Then a static-continuous effect is active
        And the effect has no specified duration but ends when the static ability becomes non-functional

    # Test for Chapter 6 introduction - Replacement effects modify events
    Scenario: Replacement effects replace an event with a modified event
        Given a game is in progress
        And a replacement effect is active
        When the event that the replacement effect monitors is about to occur
        Then the replacement effect intercepts the event
        And a modified event occurs instead of the original event

    # Test for Chapter 6 introduction - Triggered effects respond to events
    Scenario: Triggered effects respond to specific game events
        Given a card with a triggered effect is in play
        When the triggering event occurs
        Then the triggered effect is placed on the stack
        And the triggered effect resolves when it reaches the top of the stack
