# Feature file for Section 7.5: Damage Step
# Reference: Flesh and Blood Comprehensive Rules Section 7.5
#
# Rule 7.5.1: The Damage Step is a game state where the physical damage of the
# active chain link is calculated and applied.
#
# Rule 7.5.2: First, damage is calculated for the attack-target(s). If the power
# of the attack is greater than the sum total defense value of the defending cards
# for the attack-target, the attack deals {p} damage (physical damage) to the
# attack-target equal to the difference.
#
# Rule 7.5.2a: Dealing {p} damage to the attack-target this way is a hit-event
# generated by the game. The source of the damage is the attack.
#
# Rule 7.5.2b: If the attack-target has ceased to exist or is illegal when the
# damage is calculated, no damage is dealt, and the event is not generated.
#
# Rule 7.5.2c: If there are two or more attack-targets, damage is calculated and
# dealt separately for each attack-target controlled by players in clockwise-order.
# If there are two or more attack-targets controlled by the same player, the order
# is determined by the controller of the attack.
#
# Rule 7.5.3: Second, the turn-player gains priority.
#
# Rule 7.5.4: Third and finally, when the stack is empty and all players pass in
# succession, the Damage Step ends and the Resolution Step begins.
#
# Rule 7.5.5: An attack is considered to have hit if it deals damage to an
# attack-target during the Damage Step of combat. The hit-event is otherwise
# identical to a deal {p} damage event and only occurs during the Damage Step.
#
# Rule 7.5.5a: If the attack-target loses life as a result of anything except
# damage dealt by the active-attack by the hit-event during the Damage Step,
# then the attack is not considered to have hit.
#
# Rule 7.5.5b: If the hit-event is modified by replacement effects such that no
# damage is dealt by the active-attack to the attack-target, it is no longer a
# hit-event. Damage may still be dealt but it is not a hit if the active-attack
# is not the source.
#
# Rule 7.5.5c: If a rule or effect prevents a triggered effect from triggering
# when the active-attack hits and/or when it deals damage, then the triggered
# effect does not trigger on the hit-event.
#
# Rule 7.5.5d: A chain link is considered to have hit if any hit-event occurs
# while it is the active chain link.

Feature: Section 7.5 - Damage Step
    As a game engine
    I need to correctly implement the Damage Step of combat
    So that damage is calculated and applied following the comprehensive rules

    # Rule 7.5.1 — Damage Step is a distinct game state

    Scenario: Damage Step is the game state where physical damage is calculated and applied
        Given a game is in progress
        And the combat chain has an active chain link
        And the Reaction Step has ended
        When the Damage Step begins
        Then the game is in the Damage Step
        And physical damage of the active chain link is being calculated

    Scenario: Damage Step begins after the Reaction Step ends
        Given a game is in progress
        And the game is in the Reaction Step
        And the stack is empty
        And all players have passed in succession
        When the Reaction Step ends
        Then the Damage Step begins

    # Rule 7.5.2 — Damage calculation: power > total defense = damage equal to difference

    Scenario: Attack with power greater than total defense deals damage equal to the difference
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 6
        And the attack-target has defending cards with total defense 5
        When damage is calculated
        Then the attack-target is dealt 1 physical damage

    Scenario: Attack with power equal to total defense deals no damage
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 5
        And the attack-target has defending cards with total defense 5
        When damage is calculated
        Then the attack-target is dealt 0 physical damage
        And no damage event is generated

    Scenario: Attack with power less than total defense deals no damage
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 3
        And the attack-target has defending cards with total defense 5
        When damage is calculated
        Then the attack-target is dealt 0 physical damage
        And no damage event is generated

    Scenario: Defense is summed from multiple defending cards
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 6
        And the attack-target has a defending card with defense 3
        And the attack-target has a defending card with defense 2
        When damage is calculated
        Then the total defense value is 5
        And the attack-target is dealt 1 physical damage

    Scenario: Undefended attack with power 4 deals 4 damage
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 4
        And the attack-target has no defending cards
        When damage is calculated
        Then the attack-target is dealt 4 physical damage

    # Rule 7.5.2a — Hit-event is generated by the game, source is the attack

    Scenario: Damage dealt during Damage Step generates a hit-event
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 5
        And the attack-target has defending cards with total defense 3
        When damage is calculated
        Then a hit-event is generated
        And the source of the hit-event is the active attack

    Scenario: Attack that deals no damage does not generate a hit-event
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 3
        And the attack-target has defending cards with total defense 5
        When damage is calculated
        Then no hit-event is generated

    # Rule 7.5.2b — No damage if attack-target ceases to exist

    Scenario: No damage is dealt if attack-target has ceased to exist
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 6
        And the attack-target has ceased to exist before damage is calculated
        When damage is calculated
        Then no damage is dealt
        And no damage event is generated

    Scenario: No damage is dealt if attack-target is illegal
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 6
        And the attack-target is no longer a legal target
        When damage is calculated
        Then no damage is dealt
        And no damage event is generated

    # Rule 7.5.2c — Multiple attack-targets: calculated separately in clockwise order

    Scenario: Multiple attack-targets receive damage calculated separately
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 6
        And attack-target A has defending cards with total defense 2
        And attack-target B has defending cards with total defense 4
        When damage is calculated for multiple attack-targets
        Then attack-target A is dealt 4 physical damage
        And attack-target B is dealt 2 physical damage

    Scenario: Multiple attack-targets are processed in clockwise player order
        Given a game is in progress
        And the game is in the Damage Step
        And there are two attack-targets controlled by different players
        When damage is calculated for multiple attack-targets
        Then damage is calculated for each attack-target in clockwise order

    # Rule 7.5.3 — Turn-player gains priority second

    Scenario: Turn-player gains priority during the Damage Step
        Given a game is in progress
        And the game is in the Damage Step
        And damage has been calculated and applied
        When the Damage Step priority phase begins
        Then the turn-player gains priority

    # Rule 7.5.4 — Damage Step ends when stack is empty and all pass

    Scenario: Damage Step ends and Resolution Step begins when all players pass
        Given a game is in progress
        And the game is in the Damage Step
        And the turn-player has gained priority
        And the stack is empty
        And all players have passed in succession
        When the Damage Step ends
        Then the Resolution Step begins

    # Rule 7.5.5 — Hit definition: attack deals damage to attack-target during Damage Step

    Scenario: An attack is considered to have hit when it deals damage during the Damage Step
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 5
        And the attack-target has defending cards with total defense 3
        When damage is calculated
        Then the attack is considered to have hit

    Scenario: An attack is not considered to have hit when it deals no damage
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 3
        And the attack-target has defending cards with total defense 5
        When damage is calculated
        Then the attack is not considered to have hit

    Scenario: Hit-event only occurs during the Damage Step of combat
        Given a game is in progress
        And the active attack has power 5
        And the attack-target has no defending cards
        When damage is dealt outside of the Damage Step
        Then no hit-event is generated

    # Rule 7.5.5a — Life loss not by hit-event does not count as a hit

    Scenario: Life loss from effect during Damage Step is not a hit
        Given a game is in progress
        And the game is in the Damage Step
        And the attack-target loses life due to an effect unrelated to the active attack
        When the hit determination is made
        Then the attack is not considered to have hit
        And the life loss does not constitute a hit-event

    # Rule 7.5.5b — Replacement effect preventing damage means no hit

    Scenario: Replacement effect preventing all damage removes the hit-event
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 5
        And the attack-target has no defending cards
        And a replacement effect prevents all damage from the active attack to the attack-target
        When damage is calculated
        Then no damage is dealt to the attack-target
        And the attack is not considered to have hit

    Scenario: Replacement effect changing damage source removes the hit-event
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 5
        And the attack-target has no defending cards
        And a replacement effect changes the source of the damage to something other than the active attack
        When damage is calculated
        Then the attack is not considered to have hit
        And the damage event is no longer a hit-event

    # Rule 7.5.5c — Triggered effects suppressed from hit-events

    Scenario: Triggered effect suppressed from hit does not trigger
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack has power 5
        And the attack-target has no defending cards
        And an effect prevents triggered effects from triggering when the active attack hits
        When the attack hits
        Then triggered effects of the attack do not trigger on the hit-event

    # Rule 7.5.5d — Chain link has hit if any hit-event occurs while active

    Scenario: A chain link is considered to have hit if any hit-event occurs while active
        Given a game is in progress
        And the game is in the Damage Step
        And the active attack hits the attack-target
        When the hit determination is made for the chain link
        Then the active chain link is considered to have hit
