# Feature file for Section 1.8: Effects
# Reference: Flesh and Blood Comprehensive Rules Section 1.8
#
# 1.8.1 An effect is generated by an ability or another effect, and can change the game
# state by producing events or applying changes to objects or the game itself. When a
# layer resolves, a static ability becomes functional, a card/ability with an
# alternative/additional effect-cost is played/activated, or the conditions of another
# effect are met, it may generate one or more discrete and/or continuous effects.
#
# 1.8.1a The source of an effect is the same as the source of the ability or effect
# that generated it, unless otherwise specified by the effect.
#
# 1.8.1b The controller of an effect is the same as the controller of the ability or
# effect that generated it unless otherwise specified by the effect.
#
# 1.8.2 If the abilities of an object directly generate an effect, the object is
# considered an object with that effect. This includes optional and conditional effects.
#
# 1.8.3 An optional effect is an effect that the player may choose to be generated.
# An optional effect typically contains the term "may."
#
# 1.8.3a When an optional effect would be generated, or would apply to objects or
# the game, the player instructed by the effect chooses whether or not to generate
# or apply the effect.
#
# 1.8.3b If any of the optional effects cannot be generated due to a rule or effect,
# cannot resolve successfully based on the current game state, or contain an
# asset-cost which cannot be paid, the effect cannot be generated/applied and the
# player cannot choose to generate/apply the effect. If the optional effects are
# phrased with "may choose to" then the player may choose to generate the effects
# regardless of their outcome.
#
# 1.8.4 A conditional effect is an effect that is dependent on a condition to be met.
# Written in the format "(If / During) [CONDITION], [EFFECT]"
#
# 1.8.4a Conditional effect written "Otherwise [EFFECT]" - conditional on failure of
# preceding effect.
#
# 1.8.4b Conditional effect written "[EFFECT] unless [OPPCONDITION]" - conditional on
# opposite of the OPPCONDITION.
#
# 1.8.4c Conditional effect written "[EFFECT] while [CONDITION]" - applies only while
# CONDITION met, evaluated at all times.
#
# 1.8.5 A targeted effect is an effect where the target parameters are declared as the
# object is put onto the stack.
#
# 1.8.5a Only public objects in the arena or on the stack are targetable, unless the
# effect specifies otherwise.
#
# 1.8.5b The same legal target cannot be declared more than once for any one instance
# of the target phrase.
#
# 1.8.5c An effect using "target" requires target declaration; effects without "target"
# are not targeted effects.
#
# 1.8.5d If a targeted effect can only be applied to certain objects, legal targets are
# restricted.
#
# 1.8.5e If a targeted effect is optional, the player may choose not to select a target.
#
# 1.8.5f If an effect modifies the target, only legal targets for the original effect
# may be selected.
#
# 1.8.6 If the parameters of an effect are undetermined, the instructed player
# determines them. If no legal parameters exist, the effect fails.
#
# 1.8.6a Multiple players determine parameters in clockwise order starting with
# the controller.
#
# 1.8.6b Parameters for determining objects can only be public objects in arena or
# on stack, unless stated otherwise.
#
# 1.8.6c If parameters include two or more objects but there are insufficient legal
# objects, all legal objects become the parameters.
#
# 1.8.6d If an effect would generate a compound event, the player determines the order.
#
# 1.8.7 If an effect refers to the value of a property, it infers the existence of the
# property. If an object does not have that property, it does not meet the condition.
#
# 1.8.7a If an effect requires the value of a numeric property from a specific object
# without that property, then zero is used as the value.
#
# 1.8.8 If an effect instructs a player to perform an action "as though" the game state
# or rules were modified, rules and effects consider the modified game state for the
# applicable effect only.
#
# 1.8.9 An effect fails if the target(s) cease to exist, if there are no legal
# parameters at the time the effect is generated, or if all the events it creates fail.
#
# 1.8.10 "Your next attack" refers to the next attack that comes under the player's
# control; does not apply if properties change after the object comes under control.

Feature: Section 1.8 - Effects
    As a game engine
    I need to correctly implement effect generation and resolution rules
    So that card effects change the game state according to the comprehensive rules

    # Test for Rule 1.8.1 - Effect generated by ability changes game state
    Scenario: effect generated by ability changes game state
        Given a player has a card "Chain Lightning" with a damage-dealing ability
        When the ability generates a deal damage effect
        Then the effect should change the game state by dealing damage

    # Test for Rule 1.8.1a - Effect source inherits from generating ability
    Scenario: effect source is same as generating ability source
        Given a player has a card "Electrify" with a delayed triggered damage effect
        And the effect specifies the attack action card as its source
        When the effect triggers and generates a damage effect
        Then the damage effect source should be the attack action card

    # Test for Rule 1.8.1b - Effect controller inherits from generating ability
    Scenario: effect controller is same as generating ability controller
        Given player 0 controls a card with an ability
        When player 0's ability generates an effect
        Then the effect controller should be player 0

    # Test for Rule 1.8.1b - Effect with specified controller override
    Scenario: effect can specify a different controller
        Given player 0 controls a card with an ability that specifies player 1 as effect controller
        When the ability generates an effect
        Then the effect controller should be player 1

    # Test for Rule 1.8.2 - Object considered to have effect it generates
    Scenario: card with conditional damage effect is considered to have that effect
        Given a card "Chain Lightning" whose ability conditionally generates a deal 3 arcane damage effect
        When checking if Chain Lightning is a card with a deal damage effect
        Then it should be considered a card with an effect that deals arcane damage

    # Test for Rule 1.8.2 - Including optional effects
    Scenario: card with optional damage effect is considered to have that effect
        Given a card with an optional effect "may deal 2 damage"
        When checking if the card has a deal damage effect
        Then it should be considered a card with a deal damage effect

    # Test for Rule 1.8.3 - Optional effect requires player choice
    Scenario: optional effect requires player choice to generate
        Given a player has a card with an optional effect "you may banish 3 cards"
        And the player has 3 or more eligible cards
        When the optional effect would be generated
        Then the player must choose whether to generate the effect

    # Test for Rule 1.8.3a - Player chooses whether to generate optional effect
    Scenario: player can choose not to generate optional effect
        Given a player has a card with an optional effect "you may banish a card"
        And the player decides not to generate the optional effect
        When the optional effect choice is evaluated
        Then the optional effect should not be generated

    # Test for Rule 1.8.3b - Optional effect blocked when conditions unmet
    Scenario: optional effect cannot be generated when conditions are unmet
        Given a player has a card "Murky Water" with an optional effect to banish 3 traps
        And the player has fewer than 3 traps in their graveyard
        When checking if the optional effect can be generated
        Then the player cannot choose to generate the optional effect

    # Test for Rule 1.8.3b - "May choose to" phrasing allows choice regardless of outcome
    Scenario: may choose to phrasing allows choice even when effect may fail
        Given a player has a card "Mark of the Huntsman" with a "may choose to" optional effect
        And the optional effect may not fully resolve
        When checking if the player can choose to generate the effect
        Then the player may choose to generate the effect regardless of outcome

    # Test for Rule 1.8.4 - Conditional effect not generated when condition unmet
    Scenario: conditional effect is not generated when condition is not met
        Given a card "Chain Lightning" has a conditional effect "If you've played another Wizard non-attack action card this turn, deal 3 arcane damage"
        And the player has not played another Wizard non-attack action card this turn
        When the chain lightning card resolves without condition met
        Then the conditional damage effect should not be generated

    # Test for Rule 1.8.4 - Conditional effect generated when condition is met
    Scenario: conditional effect is generated when condition is met
        Given a card has a conditional effect "If you've played another Wizard non-attack action card this turn, deal 3 arcane damage"
        And the player has played another Wizard non-attack action card this turn
        When the chain lightning card resolves with condition met
        Then the deal 3 arcane damage effect should be generated

    # Test for Rule 1.8.4a - "Otherwise" conditional effect
    Scenario: otherwise effect triggers when preceding effect condition not met
        Given a card "Runeblood Incantation" has effects "If you do, create a Runechant token. Otherwise, destroy Runeblood Incantation"
        And the player cannot remove a verse counter from Runeblood Incantation
        When the card effect is evaluated
        Then the "Otherwise" effect should be generated
        And the "create Runechant token" effect should not be generated

    # Test for Rule 1.8.4a - "Otherwise" effect does not trigger when preceding condition met
    Scenario: otherwise effect does not trigger when preceding effect succeeds
        Given a card has effects "If you do, create a token. Otherwise, destroy this card"
        And the preceding effect succeeds
        When the otherwise conditional effect is evaluated
        Then the otherwise effect should not be generated

    # Test for Rule 1.8.4b - "Unless" conditional effect
    Scenario: unless effect triggers when opposite condition not met
        Given a card "Pitfall Trap" has an effect "deal 2 damage to the attacking hero unless they pay 1 resource"
        And the attacking hero does not pay the resource cost
        When the pitfall trap unless effect is evaluated
        Then the deal 2 damage effect should be generated

    # Test for Rule 1.8.4b - "Unless" conditional effect does not trigger when condition met
    Scenario: unless effect does not trigger when opposite condition is met
        Given a card has an effect "deal 2 damage unless they pay 1 resource"
        And the defending player pays the resource cost
        When the unless effect with payment is evaluated
        Then the deal damage effect should not be generated

    # Test for Rule 1.8.4c - "While" effect applies only while condition met
    Scenario: while effect applies only while condition is met
        Given a card "Parable of Humility" has an effect "attack action cards get -1 power while attacking and defending"
        And an attack action card is currently attacking
        When checking whether the while effect applies to the attacking card
        Then the effect should apply to the attacking card

    # Test for Rule 1.8.4c - "While" condition evaluated per subject
    Scenario: while condition evaluated separately for each subject
        Given a card has an effect "objects get a bonus while condition is true"
        And the effect applies to two objects
        And the condition is true for object A but false for object B
        When evaluating whether the while effect applies
        Then the effect should apply to object A
        And the effect should not apply to object B

    # Test for Rule 1.8.5 - Targeted effect requires target declaration at stack placement
    Scenario: targeted effect requires target declaration when placed on stack
        Given a player has a card with a targeted effect "deal 3 damage to target hero"
        When the targeted card is placed onto the stack
        Then a target must be declared for the targeted effect

    # Test for Rule 1.8.5a - Only public objects in arena or on stack are targetable
    Scenario: only public objects in arena or on stack are legal targets
        Given a player has a card "Frosting" with a targeted effect "deal 3 arcane damage to any target"
        And a hero is in the arena as a public object
        And a card is face-down in the player's hand
        When determining legal targets for Frosting
        Then the hero in the arena should be a legal target
        And the face-down card in hand should not be a legal target

    # Test for Rule 1.8.5a - Effect specifying zone can target that zone's objects
    Scenario: effect specifying a zone can target public objects in that zone
        Given a player has a card "Memorial Ground" with an effect targeting a card in the graveyard
        And a face-up attack card with cost 2 is in the graveyard
        And a face-down card is also in the graveyard
        When determining legal targets for Memorial Ground
        Then the face-up attack card should be a legal target
        And the face-down card should not be a legal target

    # Test for Rule 1.8.5b - Same target cannot be declared twice
    Scenario: same target cannot be declared more than once for one instance
        Given a player has an effect requiring 2 targets
        And the player selects the same target twice
        When validating the target declaration
        Then the target declaration should be invalid

    # Test for Rule 1.8.5c - Non-target effects do not use the "target" designation
    Scenario: non-target effect subjects do not need to be declared at stack placement
        Given a player has a card "Remembrance" with an effect "shuffle up to 3 action cards from your graveyard"
        When the non-targeted card is placed onto the stack
        Then no target declaration is required at this time
        And subjects are determined when the effect is generated upon resolution

    # Test for Rule 1.8.5d - Legal targets restricted by effect requirements
    Scenario: targeted effect restricts legal targets based on effect requirements
        Given a player has a card "Rewind" with an effect "negate target non-attack action card"
        And a non-attack action card is on the stack
        And an attack action card is on the stack
        When determining legal targets for Rewind
        Then the non-attack action card on stack should be a legal target
        And the attack action card should not be a legal target for Rewind

    # Test for Rule 1.8.5e - Optional targeted effect can choose no target
    Scenario: optional targeted effect allows choosing no target
        Given a player has a card with an optional targeted effect "you may deal 2 damage to target hero"
        When the player chooses not to select a target
        Then the optional targeted effect should not be generated

    # Test for Rule 1.8.5f - Target modification only allows legal targets
    Scenario: modifying a target can only select legal targets for the original effect
        Given a player has a card "Taipanis" with an effect to redirect a lethal damage source
        And the lethal damage source only has heroes as legal targets
        When Taipanis attempts to choose new targets
        Then only heroes should be valid new targets
        And the same hero's own hero should not be a valid target

    # Test for Rule 1.8.5f - No valid new target leaves original target unchanged
    Scenario: no valid new target leaves original target unchanged
        Given a player has an effect that can modify another effect's target
        And there are no other legal targets for the original targeted effect
        When the modifying effect attempts to change the target
        Then the original target should remain unchanged

    # Test for Rule 1.8.6 - Undetermined parameters resolved by instructed player
    Scenario: player determines undetermined effect parameters at resolution
        Given a player has a card "Remembrance" with an effect "shuffle up to 3 action cards from graveyard"
        And the player has 5 action cards in their graveyard
        When the card resolves and the effect is generated
        Then the player must determine which cards are the parameters
        And the player may select up to 3 of those cards

    # Test for Rule 1.8.6 - No legal parameters causes effect to fail
    Scenario: effect with no legal parameters fails
        Given a player has an effect that requires determining a target card
        And there are no eligible cards in the relevant zone
        When the no-parameter effect is generated
        Then the part of the effect related to those parameters should fail

    # Test for Rule 1.8.6a - Multiple players determine parameters clockwise
    Scenario: multiple players determine parameters in clockwise order from controller
        Given a card "Codex of Frailty" has an effect requiring all heroes to choose a card from their graveyard
        And player 0 controls the effect
        When the parameters are being determined
        Then player 0 determines their parameter first
        And the next player clockwise determines their parameter second

    # Test for Rule 1.8.6b - Parameter determination limited to public objects
    Scenario: parameter determination can only select public objects in arena or on stack
        Given a player has a card "Oasis Respite" with an effect allowing source selection
        And a face-up card is in the arena
        And a face-down card is also in the arena
        When the player determines the source parameter
        Then the face-up card should be a valid parameter choice
        And the face-down card should not be a valid parameter choice

    # Test for Rule 1.8.6c - Insufficient objects means all legal objects are parameters
    Scenario: insufficient legal objects means all legal objects become parameters
        Given a card "System Reset" has an effect "banish X items you control" with X equal to 4
        And the player only controls 2 items
        When the system reset effect is generated
        Then all 2 items should become the parameters for the banish effect

    # Test for Rule 1.8.6d - Player determines order of compound events
    Scenario: player determines order of compound event individual events
        Given a player has an effect that generates a compound event banishing multiple cards
        And the player has 3 cards to banish
        When the player determines the order of banishing
        Then the player specifies which card is banished first
        And the player specifies which card is banished second
        And the player specifies which card is banished third

    # Test for Rule 1.8.7 - Effect condition infers property existence
    Scenario: effect condition requiring property value fails for objects without that property
        Given a card "Harmonized Kodachi" has a condition "if you have a card in pitch zone with cost 0"
        And a card "Heart of Fyendal" with no cost property is in the pitch zone
        When evaluating the condition
        Then Heart of Fyendal should not satisfy the "cost 0" condition

    # Test for Rule 1.8.7 - Objects without cost property can satisfy "no cost restriction"
    Scenario: cards without cost property are not restricted by cost-based effects
        Given a card "Find Center" has an effect that restricts defending with cards of cost less than X
        And a card "Ironrot Helm" with no cost property is available to defend
        When checking if Ironrot Helm can defend Find Center
        Then Ironrot Helm should be able to defend because it has no cost property

    # Test for Rule 1.8.7a - Missing numeric property treated as zero
    Scenario: missing numeric property treated as zero in numeric effects
        Given a card "Ravenous Rabble" has an effect "this gets -X power where X is the pitch value of a revealed card"
        And the revealed card "Gorganian Tome" has no pitch property
        When calculating X for the effect
        Then X should be zero because the card has no pitch property
        And the power modifier should be 0

    # Test for Rule 1.8.8 - "As though" effects apply only for that effect
    Scenario: as though effect modifies rules only for that applicable effect
        Given a card "Teklovossen" has an effect "this counts as having 4 Evos equipped"
        When an effect counts the number of Evos equipped
        Then the count should include the 4 virtual Evos from the Teklovossen effect
        And effects interacting directly with equipped Evos should not be affected by the virtual count

    # Test for Rule 1.8.8 - "Counts as" effect modifies game state for that effect only
    Scenario: counts as effect applies only for the applicable effect
        Given a card with an effect "this counts as a weapon attack"
        And an effect that provides a bonus when attacking with a weapon
        When the weapon-counting effect is evaluated
        Then the bonus should apply because the card counts as a weapon attack for that effect
        And other effects unrelated to weapon attacks should not be affected

    # Test for Rule 1.8.9 - Effect fails when target ceases to exist
    Scenario: effect fails when its target ceases to exist before resolution
        Given a player has a targeted effect on the stack targeting a hero
        And the target hero ceases to exist before the effect resolves
        When the targeted effect attempts to resolve
        Then the targeted effect should fail

    # Test for Rule 1.8.9 - Effect does not fail if at least one event succeeds
    Scenario: effect does not fail if at least one event succeeds
        Given a player has a multi-part effect targeting two heroes
        And one target hero ceases to exist before resolution
        And the other target hero still exists
        When the effect resolves
        Then the effect should not fail overall
        And the damage should be dealt to the surviving hero

    # Test for Rule 1.8.9 - Effect fails with no legal parameters
    Scenario: effect fails when there are no legal parameters at generation time
        Given a player has an effect requiring a legal target in the arena
        And there are no legal targets currently in the arena
        When the no-target-arena effect is generated
        Then the no-legal-parameter effect should fail

    # Test for Rule 1.8.10 - "Your next attack" refers to next attack under player control
    Scenario: your next attack effect applies to the next attack that comes under control
        Given a player has an effect "your next red attack this turn gets +1 power"
        When the player plays a red attack card
        Then the +1 power bonus should apply to that red attack

    # Test for Rule 1.8.10 - Stealth replacement still counts as "next attack"
    Scenario: attack replaced by stealth still triggers next attack effect
        Given a player has an effect "your next red attack gets +1 power, your next blue gets +3 power"
        And the player plays a red attack with stealth
        And the red attack is replaced with a blue attack via Uzuri's activated ability
        When evaluating which bonus applies
        Then the blue attack should get +3 power as it is a new attack under the player's control

    # Test for Rule 1.8.10a - Already-played attack that becomes specified attack type does not get the effect
    Scenario: attack that changes properties after being played does not gain the effect
        Given a player has an effect "your next blue attack gets +3 power"
        And a player plays a red attack with stealth
        And Take Up the Mantle changes the red attack to be a copy of a blue card
        When evaluating which bonus applies to the changed attack
        Then the blue attack copy should not get +3 power
        And the reason should be that the attack was already under the player's control before becoming blue
