# Feature file for Section 6.4: Replacement Effects
# Reference: Flesh and Blood Comprehensive Rules Section 6.4
#
# Rule 6.4.1: A replacement effect is a type of effect that replaces an event with a
# modified event. A replacement effect typically specifies the conditions for the event
# to be replaced and the partial or full replacement.
#
# Rule 6.4.1a: A sub-event is an event that may occur when a replacement effect replaces
# an event. Sub-events occur when the event is replaced, before the original event, and
# may also be replaced by replacement effects.
# Example: Ward 1 destroys its source (sub-event) before the damage is prevented.
#
# Rule 6.4.2: A replacement effect is considered active if an event is about to occur
# that can be replaced by the effect.
#
# Rule 6.4.2a: The condition of replacement and any variable values are determined each
# time a replacement effect could be applied to an event.
# Example: Arcanite Fortress's Spellvoid X recalculates X each time the replacement
# effect could be applied.
#
# Rule 6.4.3: A replacement effect must exist before an event occurs to replace it. If a
# replacement effect is generated after an event occurs, it does not retroactively replace
# that event.
#
# Rule 6.4.4: A replacement effect can replace an event that has been modified by another
# replacement effect, as long as the effect is active for that modified event.
#
# Rule 6.4.5: A replacement effect can only replace an event once per original event. It
# cannot replace its own modified event, or any further modified events produced by other
# replacement effects if it has already replaced the event.
#
# Rule 6.4.6: If an event is replaced with a modified event, the event does not occur and
# the modified event occurs instead. The modified event may cause other replacement effects
# to be active that would not have been active for the replaced event.
#
# Rule 6.4.7: A self-replacement effect is a replacement effect that applies to a preceding
# effect generated by the same ability or a leading connected ability.
# Format: "[EFFECT]. [CONDITION], instead [MODIFICATION]"
# Example: Tome of Divinity: "Draw 2 cards. If a card has been put into your soul this turn,
# instead draw 3 cards."
#
# Rule 6.4.7a: A self-replacement effect does not modify any event other than the event
# created by the proceeding effect on its source.
#
# Rule 6.4.7b: The condition of a self-replacement effect is evaluated at the time the
# preceding effect is generated. If the condition is dependent on undetermined parameters,
# it is evaluated when those parameters are determined.
# Example: Weave Earth — condition evaluated when the future card is played.
#
# Rule 6.4.8: An identity-replacement effect is a replacement effect written as
# "As [CONDITION] [MODIFICATION]" or "[CONDITION] (as/with) [MODIFICATION]". Typically
# used for objects entering the arena.
# Example: Hyper Driver "This enters the arena with 3 steam counters."
#
# Rule 6.4.8a: An identity-replacement effect that modifies properties of the object
# defines its copyable properties.
#
# Rule 6.4.9: A standard-replacement effect is a continuous replacement effect written as
# "(If / The next) [CONDITION], instead [MODIFICATION]."
#
# Rule 6.4.10: A prevention effect is a replacement effect that replaces a damage event
# with a modified event. Format: "[CONDITION?] prevent [PREVENTION]."
#
# Rule 6.4.10a: For every 1 damage prevented, the prevention amount is reduced by 1.
# If prevention amount reaches 0, remaining damage is dealt as normal.
#
# Rule 6.4.10b: If prevention amount is not explicitly specified, it equals the damage
# in the event. Example: Feign Death prevents all damage from the next damage event.
#
# Rule 6.4.10c: If prevention damage type is not specified, all damage types are prevented.
# If specified, only that type is prevented.
#
# Rule 6.4.10d: If source is not specified, prevention applies to all damage to the shielded
# object regardless of source.
#
# Rule 6.4.10e: If shielded object is not specified, prevention applies to all damage dealt
# by the specified source.
#
# Rule 6.4.10f: If there are two or more damage types or shielded objects, the controller
# of the prevention effect declares which damage to prevent.
#
# Rule 6.4.10g: If an effect decreases the prevention amount, total prevention is determined,
# amount is reduced, then the prevention effect is applied with the decrease.
# Example: Vambrace of Determination reduces next prevention effect by 1.
#
# Rule 6.4.10h: If an effect states prevention cannot prevent the damage, the prevention
# effect still applies but its prevention amount is not reduced. Additional modifications
# still occur. Example: Ward effect applied to unprevented damage — source is still destroyed.
#
# Rule 6.4.10i: A fixed-prevention effect prevents a specific amount of damage from one
# triggering event. Remaining prevention is not used on subsequent events.
#
# Rule 6.4.10j: A shielding-prevention effect (shield) prevents damage across any number
# of events until the total prevention amount is reduced to zero.
#
# Rule 6.4.11: An outcome-replacement effect replaces the outcome of an event with another
# event. Format: "(If / The next) [CONDITION], instead [MODIFICATION]."
# Example: Victor's clash failure replacement effect.

Feature: Section 6.4 - Replacement Effects
    As a game engine
    I need to correctly implement replacement effects
    So that events are properly replaced with modified events

    # Rule 6.4.1 - Basic replacement effect
    Scenario: A replacement effect replaces an event with a modified event
        Given a replacement effect exists that replaces drawing 2 cards with drawing 3 cards
        And the condition for the replacement is met
        When the event of drawing 2 cards is about to occur
        Then the replacement effect replaces the event
        And the modified event of drawing 3 cards occurs instead
        And the original event of drawing 2 cards does not occur

    # Rule 6.4.1a - Sub-events
    Scenario: A sub-event occurs before the original event when a replacement effect is applied
        Given a replacement effect with a sub-event exists
        And the condition for the replacement is met
        When the replacement effect is applied to an event
        Then the sub-event occurs first
        And the sub-event occurs before the modified event

    # Rule 6.4.2 - Active replacement effect
    Scenario: A replacement effect is only active when its triggering event is about to occur
        Given a replacement effect that replaces a specific damage event
        When an event that does not match the replacement condition occurs
        Then the replacement effect is not active
        And the replacement effect does not apply to the event

    Scenario: A replacement effect becomes active when its triggering event is about to occur
        Given a replacement effect that replaces the next time a hero would be dealt damage
        When the hero is about to be dealt damage
        Then the replacement effect is active
        And the replacement effect can be applied to the event

    # Rule 6.4.2a - Variable values recalculated
    Scenario: Variable values in a replacement effect are recalculated each time it could apply
        Given a replacement effect with a variable value based on game state
        And the game state changes before the replacement effect is applied
        When the replacement effect is about to be applied
        Then the variable value is recalculated using the current game state
        And the recalculated value is used for the replacement

    # Rule 6.4.3 - Must exist before event
    Scenario: A replacement effect created after an event does not retroactively replace it
        Given an event has already occurred
        When a replacement effect is generated after the event
        Then the replacement effect does not retroactively apply to the past event
        And the event stands as it originally occurred

    # Rule 6.4.4 - Chain of replacement effects
    Scenario: A replacement effect can replace an event already modified by another replacement effect
        Given two replacement effects both active for a damage event
        And the first replacement effect modifies the damage event
        When the second replacement effect checks if it is active for the modified event
        Then the second replacement effect can be active for the modified event
        And the second replacement effect can replace the modified event

    # Rule 6.4.5 - Cannot replace own modified event
    Scenario: A replacement effect cannot replace the same event more than once per original event
        Given a replacement effect that replaces a damage event
        When the replacement effect has already been applied to the original event
        And the modified event is about to occur
        Then the replacement effect cannot replace its own modified event
        And the effect can only be applied once per original event

    # Rule 6.4.6 - Modified event triggers new effects
    Scenario: A modified event can trigger replacement effects that the original event would not have
        Given an event is about to occur
        And a replacement effect modifies the event to a different type of event
        When the replacement effect is applied and the modified event occurs
        Then replacement effects active for the modified event but not the original may apply
        And triggered effects sensitive to the modified event may fire

    # Rule 6.4.7 - Self-replacement effect
    Scenario: A self-replacement effect replaces the event of its preceding effect when condition is met
        Given a card with a draw effect and a self-replacement effect
        And the condition for the self-replacement is satisfied before the draw effect generates its event
        When the card resolves and the draw effect is generated
        Then the self-replacement effect replaces the draw event
        And the modified draw event occurs instead

    Scenario: A self-replacement effect does not apply when its condition is not met
        Given a card with a draw effect and a self-replacement effect
        And the condition for the self-replacement is NOT satisfied
        When the card resolves and the draw effect is generated
        Then the self-replacement effect does not apply
        And the original draw event occurs as normal

    # Rule 6.4.7a - Self-replacement only applies to its own preceding effect
    Scenario: A self-replacement effect only modifies the event of its own preceding effect
        Given a card with a self-replacement effect
        And another card also generates a draw effect
        When the other card's draw effect generates an event
        Then the self-replacement effect does not apply to the other card's draw event

    # Rule 6.4.7b - Condition evaluated at preceding effect generation time
    Scenario: Self-replacement condition with undetermined parameters is evaluated when parameters are determined
        Given a card with a self-replacement effect dependent on a future card's properties
        When a future card is played and its relevant property is determined
        Then the self-replacement condition is evaluated at that time
        And if the condition is met the self-replacement applies

    # Rule 6.4.8 - Identity-replacement effect
    Scenario: An identity-replacement effect modifies how an object enters the arena
        Given a card with an identity-replacement effect that specifies it enters with counters
        When the card enters the arena
        Then the identity-replacement effect applies
        And the card enters the arena with the specified counters already on it

    # Rule 6.4.8a - Identity-replacement defines copyable properties
    Scenario: An identity-replacement effect that modifies object properties defines copyable properties
        Given a card with an identity-replacement effect that sets its properties on entering arena
        When the card enters the arena with the identity-replacement applied
        Then the modifications made by the identity-replacement are part of its copyable properties

    # Rule 6.4.9 - Standard-replacement effect
    Scenario: A standard-replacement effect applies when its condition is met
        Given a continuous standard-replacement effect with a specific condition
        And the condition is currently met
        When the triggering event is about to occur
        Then the standard-replacement effect applies
        And the event is replaced by the modified event specified in the effect

    # Rule 6.4.10 / 6.4.10a - Prevention effect basics
    Scenario: A prevention effect reduces the damage dealt by its prevention amount
        Given a prevention effect that prevents 3 damage
        When a damage event of 5 damage is about to be dealt
        Then the prevention effect applies to the damage event
        And 3 damage is prevented
        And the remaining 2 damage is dealt as normal
        And the prevention effect's remaining amount is reduced to 0

    # Rule 6.4.10b - Unspecified prevention amount equals damage amount
    Scenario: A prevention effect without a specified amount prevents all damage in the event
        Given a prevention effect that prevents the next damage without specifying an amount
        When a damage event of 4 damage is about to occur
        Then the prevention amount is considered to be 4
        And all 4 damage is prevented

    # Rule 6.4.10c - Prevention damage type
    Scenario: A prevention effect with no specified type prevents all damage types
        Given a prevention effect that does not specify a damage type
        When a damage event of any damage type is about to occur
        Then the prevention effect applies to any damage type

    Scenario: A prevention effect with a specified type only prevents that damage type
        Given a prevention effect that specifies it prevents physical damage only
        When a damage event containing both physical and arcane damage is about to occur
        Then the prevention effect only prevents the physical damage
        And the arcane damage is dealt as normal

    # Rule 6.4.10g - Decreasing prevention amount
    Scenario: An effect that decreases a prevention effect's amount is applied before the prevention
        Given a prevention effect that would prevent 3 damage
        And an effect exists that reduces the next prevention effect's amount by 1
        When the prevention effect is about to apply to a damage event
        Then the total prevention is established as 3
        And the reduction effect reduces the prevention amount to 2
        And only 2 damage is prevented

    # Rule 6.4.10h - Cannot prevent still applies effect
    Scenario: When damage cannot be prevented the prevention effect still applies once but prevention amount is not reduced
        Given a prevention effect with a sub-effect that destroys its source
        And an effect states the damage cannot be prevented
        When the damage event occurs
        Then the prevention effect applies once to the event
        And no damage is prevented
        And the additional modification of the prevention effect still occurs
        And the prevention amount is not reduced

    # Rule 6.4.10i - Fixed-prevention effect
    Scenario: A fixed-prevention effect prevents damage from one triggering event only
        Given a fixed-prevention effect that prevents 3 damage from the next damage event
        When a damage event of 2 damage occurs and 2 damage is prevented
        And a second damage event then occurs
        Then the fixed-prevention effect does not apply to the second damage event
        And the remaining 1 damage from the original prevention amount is discarded

    # Rule 6.4.10j - Shielding-prevention effect
    Scenario: A shielding-prevention effect applies across multiple damage events until exhausted
        Given a shielding-prevention effect that prevents the next 4 damage
        When a first damage event of 2 damage occurs
        Then 2 damage is prevented and 2 prevention amount remains
        When a second damage event of 3 damage occurs
        Then the remaining 2 prevention amount prevents 2 of the 3 damage
        And 1 damage is dealt from the second event
        And the shielding-prevention effect's prevention amount is reduced to 0 and ceases to exist

    # Rule 6.4.11 - Outcome-replacement effect
    Scenario: An outcome-replacement effect replaces the outcome of an event with another event
        Given an outcome-replacement effect that replaces a failure outcome with another event
        And the replacement condition is met
        When the event occurs and would result in the failure outcome
        Then the outcome-replacement effect applies
        And the failure outcome is replaced with the specified replacement event
        And the original failure outcome does not occur
