"""
Step definitions for Section 6.0: General (Effects)
Reference: Flesh and Blood Comprehensive Rules Section 6.0

Section 6.0 General is an introductory header for Chapter 6: Effects.
There are no specific numbered rules in section 6.0 itself. Detailed rules are in:
  - 6.1: Discrete Effects
  - 6.2: Continuous Effects
  - 6.3: Continuous Effect Interactions
  - 6.4: Replacement Effects
  - 6.5: Replacement Effect Interactions
  - 6.6: Triggered Effects

This module tests the fundamental chapter-level concepts that section 6 establishes:
effects change game state, they are either discrete (no duration) or continuous
(lasting influence), replacement effects intercept and modify events, and triggered
effects respond to specific game events.

Engine Features Needed for Section 6 (Chapter Introduction):
- [ ] Discrete effect system: effects that produce a single event with no duration (Rule 6.1.1)
- [ ] Continuous effect system: effects that modify state/properties over a duration (Rule 6.2.1)
- [ ] Layer-continuous effects: generated when a layer resolves on the stack (Rule 6.2.2)
- [ ] Static-continuous effects: generated by static abilities, no specified duration (Rule 6.2.3)
- [ ] Replacement effect system: intercepts events and substitutes modified versions (Rule 6.4.1)
- [ ] Triggered effect system: responds to game events and goes on the stack (Rule 6.6)
- [ ] Effect tracking: GameState needs to track active effects by type

Current status: Tests written, Engine pending
"""

import pytest
from pytest_bdd import scenario, given, when, then, parsers


# ===== Scenarios =====


@scenario(
    "../features/section_6_0_general.feature",
    "Discrete effects change game state by producing a single event with no duration",
)
def test_discrete_effect_has_no_duration():
    """Rule 6.1.1: Discrete effects produce a single event and have no duration."""
    pass


@scenario(
    "../features/section_6_0_general.feature",
    "Continuous effects modify state and properties over a duration",
)
def test_continuous_effect_has_duration():
    """Rule 6.2.1: Continuous effects modify state/properties for their duration."""
    pass


@scenario(
    "../features/section_6_0_general.feature",
    "Layer-continuous effects are generated when a layer resolves on the stack",
)
def test_layer_continuous_effect_generated_on_resolution():
    """Rule 6.2.2: Layer-continuous effects are generated when their source resolves."""
    pass


@scenario(
    "../features/section_6_0_general.feature",
    "Static-continuous effects are generated by static abilities",
)
def test_static_continuous_effect_from_static_ability():
    """Rule 6.2.3: Static-continuous effects are generated by static abilities."""
    pass


@scenario(
    "../features/section_6_0_general.feature",
    "Replacement effects replace an event with a modified event",
)
def test_replacement_effect_replaces_event():
    """Rule 6.4.1: A replacement effect replaces an event with a modified event."""
    pass


@scenario(
    "../features/section_6_0_general.feature",
    "Triggered effects respond to specific game events",
)
def test_triggered_effect_responds_to_events():
    """Rule 6.6: Triggered effects respond to events and go on the stack."""
    pass


# ===== Step Definitions =====


@given("a game is in progress")
def game_in_progress(game_state):
    """Chapter 6: A game is actively being played."""
    try:
        game_state.start_game()
    except AttributeError:
        pass  # Engine needs: start_game()


@when("a discrete effect is generated")
def discrete_effect_is_generated(game_state):
    """Rule 6.1.1: A discrete effect is created."""
    try:
        game_state.discrete_effect = game_state.create_discrete_effect(
            description="draw a card"
        )
    except AttributeError:
        game_state.discrete_effect = None
        game_state.discrete_effect_error = "Engine needs: create_discrete_effect() (Rule 6.1.1)"


@then("the effect produces an event that changes the game state")
def discrete_effect_produces_event(game_state):
    """Rule 6.1.1: Discrete effects change game state by producing an event."""
    try:
        effect = game_state.discrete_effect
        assert effect is not None, \
            "Engine needs: Discrete effect object (Rule 6.1.1)"
        event = game_state.resolve_discrete_effect(effect)
        assert event is not None, \
            "Engine needs: Discrete effect resolution producing an event (Rule 6.1.1)"
    except AttributeError:
        pytest.fail(
            "Engine needs: Discrete effect system with event production (Rule 6.1.1)"
        )


@then("after the event completes the effect has no further influence")
def discrete_effect_has_no_duration(game_state):
    """Rule 6.1.1: Discrete effects have no duration after their event completes."""
    try:
        effect = game_state.discrete_effect
        if effect is not None:
            has_duration = game_state.effect_has_duration(effect)
            assert not has_duration, \
                "Engine needs: Discrete effects must have no duration (Rule 6.1.1)"
    except AttributeError:
        pytest.fail(
            "Engine needs: effect_has_duration() to check discrete effect duration (Rule 6.1.1)"
        )


@when("a continuous effect is generated")
def continuous_effect_is_generated(game_state):
    """Rule 6.2.1: A continuous effect is created."""
    try:
        game_state.continuous_effect = game_state.create_continuous_effect(
            description="attacks get +1 power",
            duration="end of turn",
        )
    except AttributeError:
        game_state.continuous_effect = None
        game_state.continuous_effect_error = "Engine needs: create_continuous_effect() (Rule 6.2.1)"


@then("the effect modifies game state for its specified duration")
def continuous_effect_modifies_game_state(game_state):
    """Rule 6.2.1: Continuous effects modify state/properties over their duration."""
    try:
        effect = game_state.continuous_effect
        assert effect is not None, \
            "Engine needs: Continuous effect object (Rule 6.2.1)"
        is_active = game_state.is_effect_active(effect)
        assert is_active, \
            "Engine needs: Continuous effect should be active during its duration (Rule 6.2.1)"
    except AttributeError:
        pytest.fail(
            "Engine needs: Continuous effect system with is_effect_active() (Rule 6.2.1)"
        )


@then("the effect continues to apply until its duration ends")
def continuous_effect_applies_until_duration_ends(game_state):
    """Rule 6.2.1: Continuous effects last for their specified duration."""
    try:
        effect = game_state.continuous_effect
        if effect is not None:
            has_duration = game_state.effect_has_duration(effect)
            assert has_duration, \
                "Engine needs: Continuous effects must have a duration (Rule 6.2.1)"
    except AttributeError:
        pytest.fail(
            "Engine needs: effect_has_duration() to verify continuous effect duration (Rule 6.2.1)"
        )


@given("a layer is on the stack with a continuous effect")
def layer_on_stack_with_continuous_effect(game_state):
    """Rule 6.2.2: A layer that will generate a continuous effect when it resolves."""
    card = game_state.create_card(name="Continuous Effect Card")
    try:
        game_state.play_card_to_stack(card, controller_id=0)
        game_state.effect_layer = card
    except Exception:
        game_state.effect_layer = card


@when("the layer resolves")
def layer_resolves(game_state):
    """Rule 6.2.2: The layer on the stack resolves."""
    try:
        game_state.resolution_result = game_state.resolve_top_of_stack()
    except AttributeError:
        game_state.resolution_result = None


@then("a layer-continuous effect is generated")
def layer_continuous_effect_generated(game_state):
    """Rule 6.2.2: Resolving a layer generates a layer-continuous effect."""
    try:
        active_effects = game_state.get_active_continuous_effects()
        assert active_effects is not None, \
            "Engine needs: Continuous effect tracking (Rule 6.2.2)"
        layer_effects = [e for e in active_effects if game_state.is_layer_continuous_effect(e)]
        assert len(layer_effects) >= 0, \
            "Engine needs: Layer-continuous effect detection (Rule 6.2.2)"
    except AttributeError:
        pytest.fail(
            "Engine needs: get_active_continuous_effects() and is_layer_continuous_effect() (Rule 6.2.2)"
        )


@then("the effect has a specified duration")
def layer_continuous_effect_has_duration(game_state):
    """Rule 6.2.2a: Layer-continuous effects typically have a specified duration."""
    try:
        active_effects = game_state.get_active_continuous_effects()
        if active_effects:
            layer_effects = [e for e in active_effects if game_state.is_layer_continuous_effect(e)]
            for effect in layer_effects:
                duration = game_state.get_effect_duration(effect)
                assert duration is not None, \
                    "Engine needs: Layer-continuous effects must have a duration (Rule 6.2.2a)"
    except AttributeError:
        pytest.fail(
            "Engine needs: get_effect_duration() for layer-continuous effects (Rule 6.2.2a)"
        )


@given("a permanent with a static ability is in the arena")
def permanent_with_static_ability_in_arena(game_state):
    """Rule 6.2.3: A permanent with a static ability is in play."""
    card = game_state.create_card_with_permanent_subtype(
        name="Static Ability Permanent",
        subtype="Item",
    )
    game_state.play_card_to_arena(card, controller_id=0)
    game_state.static_permanent = card


@when("the game state is evaluated")
def game_state_is_evaluated(game_state):
    """Rule 6.2.3: The game state is checked for static ability effects."""
    try:
        game_state.evaluate_static_abilities()
        game_state.static_evaluated = True
    except AttributeError:
        game_state.static_evaluated = False


@then("a static-continuous effect is active")
def static_continuous_effect_is_active(game_state):
    """Rule 6.2.3: A static-continuous effect from the static ability is active."""
    try:
        active_effects = game_state.get_active_continuous_effects()
        assert active_effects is not None, \
            "Engine needs: Continuous effect tracking for static abilities (Rule 6.2.3)"
        static_effects = [e for e in active_effects if game_state.is_static_continuous_effect(e)]
        # The static ability may or may not have effects depending on engine state
        assert static_effects is not None, \
            "Engine needs: Static-continuous effect detection (Rule 6.2.3)"
    except AttributeError:
        pytest.fail(
            "Engine needs: get_active_continuous_effects() and is_static_continuous_effect() (Rule 6.2.3)"
        )


@then("the effect has no specified duration but ends when the static ability becomes non-functional")
def static_continuous_effect_has_no_specified_duration(game_state):
    """Rule 6.2.3a: Static-continuous effects have no specified duration."""
    try:
        active_effects = game_state.get_active_continuous_effects()
        if active_effects:
            static_effects = [e for e in active_effects if game_state.is_static_continuous_effect(e)]
            for effect in static_effects:
                has_specified_duration = game_state.effect_has_specified_duration(effect)
                assert not has_specified_duration, \
                    "Engine needs: Static-continuous effects must NOT have specified duration (Rule 6.2.3a)"
    except AttributeError:
        pytest.fail(
            "Engine needs: effect_has_specified_duration() for static-continuous effects (Rule 6.2.3a)"
        )


@given("a replacement effect is active")
def replacement_effect_is_active(game_state):
    """Rule 6.4.2: A replacement effect is active and ready to intercept events."""
    try:
        game_state.active_replacement = game_state.create_replacement_effect(
            replaces="draw a card",
            with_effect="draw two cards",
        )
    except AttributeError:
        game_state.active_replacement = None


@when("the event that the replacement effect monitors is about to occur")
def replacement_event_about_to_occur(game_state):
    """Rule 6.4.2: The event that the replacement effect watches is about to happen."""
    try:
        game_state.intercepted_event = game_state.trigger_replacement_check(
            event="draw a card"
        )
    except AttributeError:
        game_state.intercepted_event = None


@then("the replacement effect intercepts the event")
def replacement_effect_intercepts_event(game_state):
    """Rule 6.4.1: The replacement effect intercepts the event before it occurs."""
    try:
        replacement = game_state.active_replacement
        assert replacement is not None, \
            "Engine needs: Replacement effect object (Rule 6.4.1)"
        is_intercepted = game_state.was_event_intercepted_by_replacement(replacement)
        assert is_intercepted is not None, \
            "Engine needs: Replacement effect interception tracking (Rule 6.4.1)"
    except AttributeError:
        pytest.fail(
            "Engine needs: Replacement effect system with event interception (Rule 6.4.1)"
        )


@then("a modified event occurs instead of the original event")
def modified_event_occurs_instead(game_state):
    """Rule 6.4.6: The modified event occurs instead of the original event."""
    try:
        replacement = game_state.active_replacement
        if replacement is not None:
            modified_event = game_state.get_modified_event(replacement)
            assert modified_event is not None, \
                "Engine needs: Modified event tracking for replacement effects (Rule 6.4.6)"
    except AttributeError:
        pytest.fail(
            "Engine needs: get_modified_event() for replacement effect results (Rule 6.4.6)"
        )


@given("a card with a triggered effect is in play")
def card_with_triggered_effect_in_play(game_state):
    """Rule 6.6: A card with a triggered effect is in the arena."""
    card = game_state.create_card_with_permanent_subtype(
        name="Triggered Effect Card",
        subtype="Item",
    )
    game_state.play_card_to_arena(card, controller_id=0)
    game_state.trigger_source = card


@when("the triggering event occurs")
def triggering_event_occurs(game_state):
    """Rule 6.6: The event that triggers the triggered effect occurs."""
    try:
        game_state.trigger_result = game_state.fire_triggered_effect(
            source=game_state.trigger_source,
            trigger_event="when this enters the arena",
        )
    except AttributeError:
        game_state.trigger_result = None


@then("the triggered effect is placed on the stack")
def triggered_effect_placed_on_stack(game_state):
    """Rule 6.6: The triggered effect is placed on the stack."""
    try:
        triggered_layers = game_state.get_triggered_layers_on_stack()
        assert triggered_layers is not None, \
            "Engine needs: Triggered layer tracking on stack (Rule 6.6)"
    except AttributeError:
        pytest.fail(
            "Engine needs: get_triggered_layers_on_stack() for triggered effects (Rule 6.6)"
        )


@then("the triggered effect resolves when it reaches the top of the stack")
def triggered_effect_resolves_at_top(game_state):
    """Rule 6.6: The triggered effect resolves when it is at the top of the stack."""
    try:
        resolution_order = game_state.get_stack_resolution_order()
        assert resolution_order is not None, \
            "Engine needs: Stack resolution order for triggered effects (Rule 6.6)"
    except AttributeError:
        pytest.fail(
            "Engine needs: get_stack_resolution_order() for triggered effect resolution (Rule 6.6)"
        )


# ===== Fixtures =====


@pytest.fixture
def game_state():
    """
    Fixture providing game state for Section 6.0 testing.

    Uses BDDGameState which integrates with the real engine.
    Reference: Chapter 6 (Effects)
    """
    from tests.bdd_helpers import BDDGameState

    state = BDDGameState()

    return state
