"""
Step definitions for Section 7.5: Damage Step
Reference: Flesh and Blood Comprehensive Rules Section 7.5

This module implements behavioral tests for the Damage Step of combat:
the game state where physical damage of the active chain link is calculated
and applied.

Engine Features Needed for Section 7.5:
- [ ] CombatState.damage_step_active property — tracks Damage Step (Rule 7.5.1)
- [ ] CombatState.current_step property — "layer"|"attack"|"defend"|"reaction"|"damage"|"resolution"|"close"
- [ ] DamageStep.begin() — starts Damage Step after Reaction Step ends (Rule 7.5.1)
- [ ] DamageStep.end() — ends Damage Step and begins Resolution Step (Rule 7.5.4)
- [ ] ResolutionStep.begin() — begins Resolution Step after Damage Step ends (Rule 7.5.4)
- [ ] DamageStep.calculate_damage(chain_link) -> DamageResult — calculates damage (Rule 7.5.2)
- [ ] DamageStep.apply_damage(chain_link) — applies damage to attack-targets (Rule 7.5.2)
- [ ] ChainLink.total_defense_value property — sum of defense of all defending cards (Rule 7.5.2)
- [ ] ChainLink.attack_power property — power of the active attack (Rule 7.5.2)
- [ ] HitEvent.generate(chain_link) — creates a hit-event (Rule 7.5.2a)
- [ ] HitEvent.source property — the attack that is the source (Rule 7.5.2a)
- [ ] AttackTarget.exists property — whether target still exists (Rule 7.5.2b)
- [ ] AttackTarget.is_legal property — whether target is still legal (Rule 7.5.2b)
- [ ] CombatState.attack_targets list — all current attack-targets (Rule 7.5.2c)
- [ ] DamageStep.calculate_damage_for_target(target) — per-target damage calculation (Rule 7.5.2c)
- [ ] PrioritySystem.grant_priority_to_turn_player() — turn-player gains priority (Rule 7.5.3)
- [ ] PrioritySystem.all_players_passed() -> bool — check if all passed (Rule 7.5.4)
- [ ] Stack.is_empty property — whether the stack currently has items (Rule 7.5.4)
- [ ] ChainLink.has_hit property — whether the chain link is considered to have hit (Rule 7.5.5d)
- [ ] HitEvent.is_hit_event property — whether an event qualifies as a hit-event (Rule 7.5.5)
- [ ] ReplacementEffect.prevents_damage(source, target) -> bool — replacement effects (Rule 7.5.5b)
- [ ] ReplacementEffect.changes_source(hit_event) -> bool — source-changing replacements (Rule 7.5.5b)
- [ ] TriggerSuppression.suppresses_hit_triggers(attack) -> bool — suppression check (Rule 7.5.5c)

Current status: Tests written, Engine pending
"""

import pytest
from pytest_bdd import scenario, given, when, then, parsers


# ===== Scenarios =====

# Rule 7.5.1 — Damage Step is a distinct game state

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Damage Step is the game state where physical damage is calculated and applied",
)
def test_damage_step_is_game_state():
    """Rule 7.5.1: The Damage Step is a distinct game state for damage calculation."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Damage Step begins after the Reaction Step ends",
)
def test_damage_step_begins_after_reaction_step():
    """Rule 7.4.3 → 7.5.1: Damage Step begins after the Reaction Step ends."""
    pass


# Rule 7.5.2 — Damage calculation

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Attack with power greater than total defense deals damage equal to the difference",
)
def test_damage_equals_power_minus_defense():
    """Rule 7.5.2: Damage equals power minus total defense value when power > defense."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Attack with power equal to total defense deals no damage",
)
def test_no_damage_when_power_equals_defense():
    """Rule 7.5.2: No damage is dealt when power equals total defense."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Attack with power less than total defense deals no damage",
)
def test_no_damage_when_power_less_than_defense():
    """Rule 7.5.2: No damage when power is less than total defense."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Defense is summed from multiple defending cards",
)
def test_defense_summed_from_multiple_defenders():
    """Rule 7.5.2: Defense values from multiple defending cards are summed."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Undefended attack with power 4 deals 4 damage",
)
def test_undefended_attack_deals_full_damage():
    """Rule 7.5.2: An undefended attack deals damage equal to its full power."""
    pass


# Rule 7.5.2a — Hit-event generated by the game

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Damage dealt during Damage Step generates a hit-event",
)
def test_damage_generates_hit_event():
    """Rule 7.5.2a: Dealing damage this way generates a hit-event."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Attack that deals no damage does not generate a hit-event",
)
def test_no_hit_event_when_no_damage():
    """Rule 7.5.2a: No hit-event is generated when power does not exceed defense."""
    pass


# Rule 7.5.2b — Attack-target ceases to exist

@scenario(
    "../features/section_7_5_damage_step.feature",
    "No damage is dealt if attack-target has ceased to exist",
)
def test_no_damage_if_target_ceased_to_exist():
    """Rule 7.5.2b: No damage dealt when attack-target ceased to exist."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "No damage is dealt if attack-target is illegal",
)
def test_no_damage_if_target_illegal():
    """Rule 7.5.2b: No damage dealt when attack-target is illegal."""
    pass


# Rule 7.5.2c — Multiple attack-targets

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Multiple attack-targets receive damage calculated separately",
)
def test_multiple_targets_damage_calculated_separately():
    """Rule 7.5.2c: Damage is calculated and dealt separately for each attack-target."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Multiple attack-targets are processed in clockwise player order",
)
def test_multiple_targets_processed_in_clockwise_order():
    """Rule 7.5.2c: Multiple attack-targets processed in clockwise player order."""
    pass


# Rule 7.5.3 — Turn-player gains priority

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Turn-player gains priority during the Damage Step",
)
def test_turn_player_gains_priority():
    """Rule 7.5.3: Turn-player gains priority during the Damage Step."""
    pass


# Rule 7.5.4 — Damage Step ends when all pass

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Damage Step ends and Resolution Step begins when all players pass",
)
def test_damage_step_ends_resolution_step_begins():
    """Rule 7.5.4: Damage Step ends and Resolution Step begins when stack is empty and all pass."""
    pass


# Rule 7.5.5 — Hit definition

@scenario(
    "../features/section_7_5_damage_step.feature",
    "An attack is considered to have hit when it deals damage during the Damage Step",
)
def test_attack_considered_hit_when_damage_dealt():
    """Rule 7.5.5: Attack has hit if it deals damage to attack-target during Damage Step."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "An attack is not considered to have hit when it deals no damage",
)
def test_attack_not_hit_when_no_damage():
    """Rule 7.5.5: Attack is not considered to have hit when it deals no damage."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Hit-event only occurs during the Damage Step of combat",
)
def test_hit_event_only_during_damage_step():
    """Rule 7.5.5: Hit-event only occurs during the Damage Step of combat."""
    pass


# Rule 7.5.5a — Life loss by non-hit-event means no hit

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Life loss from effect during Damage Step is not a hit",
)
def test_life_loss_from_effect_not_a_hit():
    """Rule 7.5.5a: Life loss from anything other than the hit-event is not a hit."""
    pass


# Rule 7.5.5b — Replacement effect preventing damage removes hit

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Replacement effect preventing all damage removes the hit-event",
)
def test_replacement_effect_prevents_hit():
    """Rule 7.5.5b: If replacement effect prevents all damage, the hit-event does not occur."""
    pass


@scenario(
    "../features/section_7_5_damage_step.feature",
    "Replacement effect changing damage source removes the hit-event",
)
def test_replacement_effect_changes_source_removes_hit():
    """Rule 7.5.5b: If damage source changes, it is no longer a hit-event."""
    pass


# Rule 7.5.5c — Triggered effects suppressed from hit

@scenario(
    "../features/section_7_5_damage_step.feature",
    "Triggered effect suppressed from hit does not trigger",
)
def test_suppressed_triggered_effect_does_not_trigger():
    """Rule 7.5.5c: If effect prevents triggered effects from triggering on hit, they don't trigger."""
    pass


# Rule 7.5.5d — Chain link has hit if any hit-event occurs

@scenario(
    "../features/section_7_5_damage_step.feature",
    "A chain link is considered to have hit if any hit-event occurs while active",
)
def test_chain_link_has_hit():
    """Rule 7.5.5d: A chain link has hit if any hit-event occurs while it is active."""
    pass


# ===== Step Definitions =====

# --- Given steps ---

@given("a game is in progress")
def game_in_progress(damage_step_state):
    """Setup: A game is currently in progress."""
    assert damage_step_state is not None


@given("the combat chain has an active chain link")
def combat_chain_has_active_chain_link(damage_step_state):
    """Setup: There is an active chain link on the combat chain."""
    damage_step_state.has_active_chain_link = True


@given("the Reaction Step has ended")
def reaction_step_ended(damage_step_state):
    """Rule 7.4.3: The Reaction Step has completed."""
    damage_step_state.reaction_step_completed = True


@given("the game is in the Damage Step")
def game_is_in_damage_step(damage_step_state):
    """Setup: The game is currently in the Damage Step."""
    damage_step_state.begin_damage_step()


@given("the game is in the Reaction Step")
def game_is_in_reaction_step(damage_step_state):
    """Setup: The game is currently in the Reaction Step."""
    damage_step_state.current_step = "reaction"


@given("the stack is empty")
def stack_is_empty(damage_step_state):
    """Setup: The stack has no items."""
    damage_step_state.stack_empty = True


@given("all players have passed in succession")
def all_players_passed(damage_step_state):
    """Setup: All players have passed priority in succession."""
    damage_step_state.all_players_passed = True


@given(parsers.parse("the active attack has power {power:d}"))
def active_attack_has_power(damage_step_state, power):
    """Setup: The active attack has the specified power value."""
    damage_step_state.attack_power = power


@given(parsers.parse("the attack-target has defending cards with total defense {defense:d}"))
def attack_target_has_defending_cards_with_defense(damage_step_state, defense):
    """Setup: The attack-target has defending cards with specified total defense."""
    damage_step_state.total_defense = defense


@given("the attack-target has no defending cards")
def attack_target_has_no_defenders(damage_step_state):
    """Setup: No cards are defending the attack-target."""
    damage_step_state.total_defense = 0


@given(parsers.parse("the attack-target has a defending card with defense {defense:d}"))
def attack_target_has_defending_card_with_defense(damage_step_state, defense):
    """Setup: The attack-target has a defending card with specified defense value."""
    damage_step_state.defending_cards.append({"defense": defense})
    damage_step_state.total_defense = sum(c["defense"] for c in damage_step_state.defending_cards)


@given("the attack-target has ceased to exist before damage is calculated")
def attack_target_ceased_to_exist(damage_step_state):
    """Rule 7.5.2b: The attack-target no longer exists."""
    damage_step_state.attack_target_exists = False


@given("the attack-target is no longer a legal target")
def attack_target_is_illegal(damage_step_state):
    """Rule 7.5.2b: The attack-target is no longer a legal target."""
    damage_step_state.attack_target_legal = False


@given(parsers.parse("attack-target A has defending cards with total defense {defense:d}"))
def attack_target_a_has_defense(damage_step_state, defense):
    """Rule 7.5.2c: Attack-target A has the specified total defense."""
    damage_step_state.target_a_defense = defense


@given(parsers.parse("attack-target B has defending cards with total defense {defense:d}"))
def attack_target_b_has_defense(damage_step_state, defense):
    """Rule 7.5.2c: Attack-target B has the specified total defense."""
    damage_step_state.target_b_defense = defense


@given("there are two attack-targets controlled by different players")
def two_attack_targets_different_players(damage_step_state):
    """Rule 7.5.2c: Two attack-targets controlled by different players."""
    damage_step_state.multiple_attack_targets = True
    damage_step_state.attack_targets_clockwise_order = ["player_a_target", "player_b_target"]


@given("damage has been calculated and applied")
def damage_calculated_and_applied(damage_step_state):
    """Setup: Damage has already been calculated and applied."""
    damage_step_state.damage_applied = True


@given("the turn-player has gained priority")
def turn_player_has_priority(damage_step_state):
    """Rule 7.5.3: The turn-player currently has priority."""
    damage_step_state.turn_player_has_priority = True


@given("the attack-target loses life due to an effect unrelated to the active attack")
def attack_target_loses_life_from_unrelated_effect(damage_step_state):
    """Rule 7.5.5a: Life loss comes from an effect, not the hit-event."""
    damage_step_state.life_loss_from_effect = True
    damage_step_state.life_loss_source = "unrelated_effect"


@given("a replacement effect prevents all damage from the active attack to the attack-target")
def replacement_effect_prevents_damage(damage_step_state):
    """Rule 7.5.5b: A replacement effect (e.g. Feign Death) prevents all damage."""
    damage_step_state.has_damage_prevention_effect = True


@given("a replacement effect changes the source of the damage to something other than the active attack")
def replacement_effect_changes_source(damage_step_state):
    """Rule 7.5.5b: A replacement effect changes the damage source."""
    damage_step_state.has_source_change_effect = True


@given("an effect prevents triggered effects from triggering when the active attack hits")
def effect_suppresses_hit_triggers(damage_step_state):
    """Rule 7.5.5c: An effect (e.g. Stamp Authority) suppresses hit triggers."""
    damage_step_state.hit_triggers_suppressed = True


@given("the active attack hits the attack-target")
def active_attack_hits(damage_step_state):
    """Setup: The active attack has dealt damage and generated a hit-event."""
    damage_step_state.attack_power = 5
    damage_step_state.total_defense = 0
    damage_step_state.calculate_damage()


# --- When steps ---

@when("the Damage Step begins")
def damage_step_begins(damage_step_state):
    """Rule 7.5.1: The Damage Step has started."""
    damage_step_state.begin_damage_step()


@when("the Reaction Step ends")
def reaction_step_ends(damage_step_state):
    """Rule 7.4.3: The Reaction Step has ended."""
    damage_step_state.reaction_step_completed = True
    damage_step_state.begin_damage_step()


@when("damage is calculated")
def damage_is_calculated(damage_step_state):
    """Rule 7.5.2: Damage calculation occurs."""
    damage_step_state.calculate_damage()


@when("damage is calculated for multiple attack-targets")
def damage_calculated_for_multiple_targets(damage_step_state):
    """Rule 7.5.2c: Damage is calculated for multiple attack-targets."""
    damage_step_state.calculate_damage_multiple_targets()


@when("the Damage Step priority phase begins")
def damage_step_priority_phase(damage_step_state):
    """Rule 7.5.3: Priority phase of the Damage Step begins."""
    damage_step_state.begin_priority_phase()


@when("the Damage Step ends")
def damage_step_ends(damage_step_state):
    """Rule 7.5.4: All players have passed in succession and the Damage Step ends."""
    damage_step_state.end_damage_step()


@when("the hit determination is made")
def hit_determination_made(damage_step_state):
    """Rule 7.5.5: The hit determination is evaluated."""
    damage_step_state.evaluate_hit()


@when("damage is dealt outside of the Damage Step")
def damage_dealt_outside_damage_step(damage_step_state):
    """Rule 7.5.5: Damage is dealt in a non-Damage Step context."""
    damage_step_state.current_step = "resolution"
    damage_step_state.calculate_damage()


@when("the attack hits")
def attack_hits(damage_step_state):
    """Rule 7.5.5c: The attack hits the attack-target."""
    damage_step_state.calculate_damage()


@when("the hit determination is made for the chain link")
def hit_determination_for_chain_link(damage_step_state):
    """Rule 7.5.5d: The hit determination is made for the active chain link."""
    damage_step_state.evaluate_chain_link_hit()


# --- Then steps ---

@then("the game is in the Damage Step")
def game_is_in_damage_step_then(damage_step_state):
    """Rule 7.5.1: The current step is the Damage Step."""
    result = damage_step_state.get_current_step()
    assert result.step_name == "damage", (
        f"Expected game to be in Damage Step, got: {result.step_name}"
    )


@then("physical damage of the active chain link is being calculated")
def physical_damage_being_calculated(damage_step_state):
    """Rule 7.5.1: Physical damage calculation is occurring."""
    result = damage_step_state.get_current_step()
    assert result.damage_calculation_active, (
        "Expected damage calculation to be active during Damage Step"
    )


@then("the Damage Step begins")
def damage_step_begins_then(damage_step_state):
    """Rule 7.5.1: The Damage Step has started."""
    result = damage_step_state.get_current_step()
    assert result.step_name == "damage", (
        f"Expected Damage Step to begin, got: {result.step_name}"
    )


@then(parsers.parse("the attack-target is dealt {damage:d} physical damage"))
def attack_target_dealt_damage(damage_step_state, damage):
    """Rule 7.5.2: The attack-target received the specified amount of physical damage."""
    result = damage_step_state.get_damage_result()
    assert result.damage_dealt == damage, (
        f"Expected {damage} physical damage dealt, got: {result.damage_dealt}"
    )


@then("no damage event is generated")
def no_damage_event_generated(damage_step_state):
    """Rule 7.5.2: No damage event was generated."""
    result = damage_step_state.get_damage_result()
    assert not result.event_generated, (
        "Expected no damage event to be generated"
    )


@then(parsers.parse("the total defense value is {total:d}"))
def total_defense_value_is(damage_step_state, total):
    """Rule 7.5.2: The sum of all defending cards' defense values equals the expected total."""
    result = damage_step_state.get_damage_result()
    assert result.total_defense == total, (
        f"Expected total defense of {total}, got: {result.total_defense}"
    )


@then("a hit-event is generated")
def hit_event_generated(damage_step_state):
    """Rule 7.5.2a: A hit-event was generated."""
    result = damage_step_state.get_damage_result()
    assert result.hit_event_generated, (
        "Expected a hit-event to be generated"
    )


@then("the source of the hit-event is the active attack")
def source_of_hit_event_is_active_attack(damage_step_state):
    """Rule 7.5.2a: The source of the hit-event is the active attack."""
    result = damage_step_state.get_damage_result()
    assert result.hit_event_source == "active_attack", (
        f"Expected hit-event source to be active attack, got: {result.hit_event_source}"
    )


@then("no hit-event is generated")
def no_hit_event_generated(damage_step_state):
    """Rule 7.5.2a / 7.5.5: No hit-event was generated."""
    result = damage_step_state.get_damage_result()
    assert not result.hit_event_generated, (
        "Expected no hit-event to be generated"
    )


@then("no damage is dealt")
def no_damage_dealt(damage_step_state):
    """Rule 7.5.2b: No damage was dealt to the attack-target."""
    result = damage_step_state.get_damage_result()
    assert result.damage_dealt == 0, (
        f"Expected 0 damage dealt, got: {result.damage_dealt}"
    )


@then(parsers.parse("attack-target A is dealt {damage:d} physical damage"))
def attack_target_a_dealt_damage(damage_step_state, damage):
    """Rule 7.5.2c: Attack-target A received the specified damage."""
    result = damage_step_state.get_multi_target_result()
    assert result.target_a_damage == damage, (
        f"Expected attack-target A to receive {damage} damage, got: {result.target_a_damage}"
    )


@then(parsers.parse("attack-target B is dealt {damage:d} physical damage"))
def attack_target_b_dealt_damage(damage_step_state, damage):
    """Rule 7.5.2c: Attack-target B received the specified damage."""
    result = damage_step_state.get_multi_target_result()
    assert result.target_b_damage == damage, (
        f"Expected attack-target B to receive {damage} damage, got: {result.target_b_damage}"
    )


@then("damage is calculated for each attack-target in clockwise order")
def damage_calculated_in_clockwise_order(damage_step_state):
    """Rule 7.5.2c: Damage is calculated for attack-targets in clockwise order."""
    result = damage_step_state.get_multi_target_result()
    assert result.processed_in_clockwise_order, (
        "Expected attack-targets to be processed in clockwise order"
    )


@then("the turn-player gains priority")
def turn_player_gains_priority(damage_step_state):
    """Rule 7.5.3: The turn-player has been granted priority."""
    result = damage_step_state.get_priority_result()
    assert result.turn_player_has_priority, (
        "Expected turn-player to gain priority during Damage Step"
    )


@then("the Resolution Step begins")
def resolution_step_begins(damage_step_state):
    """Rule 7.5.4: The Resolution Step has begun after the Damage Step."""
    result = damage_step_state.get_current_step()
    assert result.step_name == "resolution", (
        f"Expected Resolution Step to begin, got: {result.step_name}"
    )


@then("the attack is considered to have hit")
def attack_considered_to_have_hit(damage_step_state):
    """Rule 7.5.5: The attack is considered to have hit the attack-target."""
    result = damage_step_state.get_hit_result()
    assert result.attack_hit, (
        "Expected attack to be considered to have hit"
    )


@then("the attack is not considered to have hit")
def attack_not_considered_to_have_hit(damage_step_state):
    """Rule 7.5.5 / 7.5.5a / 7.5.5b: The attack is not considered to have hit."""
    result = damage_step_state.get_hit_result()
    assert not result.attack_hit, (
        "Expected attack to NOT be considered to have hit"
    )


@then("the life loss does not constitute a hit-event")
def life_loss_not_a_hit_event(damage_step_state):
    """Rule 7.5.5a: Life loss from an unrelated effect is not a hit-event."""
    result = damage_step_state.get_hit_result()
    assert not result.life_loss_was_hit_event, (
        "Expected life loss from effect to not be a hit-event"
    )


@then("no damage is dealt to the attack-target")
def no_damage_dealt_to_target(damage_step_state):
    """Rule 7.5.5b: The replacement effect prevented all damage."""
    result = damage_step_state.get_damage_result()
    assert result.damage_dealt == 0, (
        f"Expected no damage dealt to attack-target, got: {result.damage_dealt}"
    )


@then("the damage event is no longer a hit-event")
def damage_event_not_a_hit_event(damage_step_state):
    """Rule 7.5.5b: The damage event does not qualify as a hit-event."""
    result = damage_step_state.get_hit_result()
    assert not result.event_is_hit_event, (
        "Expected the damage event to not be a hit-event"
    )


@then("triggered effects of the attack do not trigger on the hit-event")
def triggered_effects_do_not_trigger_on_hit(damage_step_state):
    """Rule 7.5.5c: Triggered effects are suppressed from the hit-event."""
    result = damage_step_state.get_hit_result()
    assert not result.triggered_effects_fired, (
        "Expected triggered effects to be suppressed from the hit-event"
    )


@then("the active chain link is considered to have hit")
def active_chain_link_considered_to_have_hit(damage_step_state):
    """Rule 7.5.5d: The active chain link is considered to have hit."""
    result = damage_step_state.get_chain_link_hit_result()
    assert result.chain_link_has_hit, (
        "Expected the active chain link to be considered to have hit"
    )


# ===== Fixtures =====

@pytest.fixture
def damage_step_state():
    """
    Fixture providing game state for Damage Step tests.

    Uses DamageStepStateStub which tracks damage step state for testing.
    Reference: Rule 7.5
    """
    return DamageStepStateStub()


# ===== Stubs =====

class DamageStepResultStub:
    """Result of a damage calculation operation."""

    def __init__(
        self,
        damage_dealt: int = 0,
        event_generated: bool = False,
        hit_event_generated: bool = False,
        hit_event_source: str = "",
        total_defense: int = 0,
    ):
        self.damage_dealt = damage_dealt
        self.event_generated = event_generated
        self.hit_event_generated = hit_event_generated
        self.hit_event_source = hit_event_source
        self.total_defense = total_defense


class MultiTargetDamageResultStub:
    """Result of a multi-target damage calculation."""

    def __init__(
        self,
        target_a_damage: int = 0,
        target_b_damage: int = 0,
        processed_in_clockwise_order: bool = False,
    ):
        self.target_a_damage = target_a_damage
        self.target_b_damage = target_b_damage
        self.processed_in_clockwise_order = processed_in_clockwise_order


class StepResultStub:
    """Result of querying the current game step."""

    def __init__(self, step_name: str = "", damage_calculation_active: bool = False):
        self.step_name = step_name
        self.damage_calculation_active = damage_calculation_active


class PriorityResultStub:
    """Result of a priority check."""

    def __init__(self, turn_player_has_priority: bool = False):
        self.turn_player_has_priority = turn_player_has_priority


class HitResultStub:
    """Result of a hit determination."""

    def __init__(
        self,
        attack_hit: bool = False,
        life_loss_was_hit_event: bool = False,
        event_is_hit_event: bool = False,
        triggered_effects_fired: bool = False,
    ):
        self.attack_hit = attack_hit
        self.life_loss_was_hit_event = life_loss_was_hit_event
        self.event_is_hit_event = event_is_hit_event
        self.triggered_effects_fired = triggered_effects_fired


class ChainLinkHitResultStub:
    """Result of querying whether a chain link has hit."""

    def __init__(self, chain_link_has_hit: bool = False):
        self.chain_link_has_hit = chain_link_has_hit


class DamageStepStateStub:
    """
    State tracker for Damage Step BDD tests.

    Wraps the engine's damage step logic for testing.
    Reference: Rule 7.5
    """

    def __init__(self):
        self.current_step = "reaction"
        self.has_active_chain_link = False
        self.reaction_step_completed = False
        self.damage_step_active = False
        self.damage_applied = False
        self.stack_empty = True
        self.all_players_passed = False
        self.turn_player_has_priority = False

        # Attack state
        self.attack_power = 0
        self.total_defense = 0
        self.defending_cards = []

        # Attack target state
        self.attack_target_exists = True
        self.attack_target_legal = True

        # Multiple target state
        self.multiple_attack_targets = False
        self.attack_targets_clockwise_order = []
        self.target_a_defense = 0
        self.target_b_defense = 0

        # Effect state
        self.life_loss_from_effect = False
        self.life_loss_source = ""
        self.has_damage_prevention_effect = False
        self.has_source_change_effect = False
        self.hit_triggers_suppressed = False

        # Results
        self._damage_result = None
        self._multi_target_result = None
        self._hit_result = None
        self._chain_link_hit_result = None

    def begin_damage_step(self):
        """Begin the Damage Step."""
        try:
            from fab_engine.combat.damage_step import DamageStep
            step = DamageStep()
            step.begin()
            self.current_step = "damage"
            self.damage_step_active = True
        except (ImportError, AttributeError):
            # Missing engine feature - expected during BDD spec phase
            self.current_step = "damage"
            self.damage_step_active = True

    def end_damage_step(self):
        """End the Damage Step and begin the Resolution Step."""
        try:
            from fab_engine.combat.damage_step import DamageStep
            step = DamageStep()
            step.end()
            self.current_step = "resolution"
        except (ImportError, AttributeError):
            self.current_step = "resolution"

    def calculate_damage(self):
        """Calculate damage for the active attack."""
        try:
            from fab_engine.combat.damage_step import DamageStep
            step = DamageStep()
            result = step.calculate_damage(
                attack_power=self.attack_power,
                total_defense=self.total_defense,
                target_exists=self.attack_target_exists,
                target_legal=self.attack_target_legal,
                in_damage_step=(self.current_step == "damage"),
                has_damage_prevention=self.has_damage_prevention_effect,
                has_source_change=self.has_source_change_effect,
                life_loss_from_effect=self.life_loss_from_effect,
                hit_triggers_suppressed=self.hit_triggers_suppressed,
            )
            self._damage_result = result
        except (ImportError, AttributeError, TypeError):
            # Missing engine feature - build stub result from local state
            self._build_damage_result_from_state()

    def _build_damage_result_from_state(self):
        """Build damage result from local state for testing."""
        if not self.attack_target_exists or not self.attack_target_legal:
            self._damage_result = DamageStepResultStub(
                damage_dealt=0,
                event_generated=False,
                hit_event_generated=False,
            )
            return

        if self.has_damage_prevention_effect:
            self._damage_result = DamageStepResultStub(
                damage_dealt=0,
                event_generated=False,
                hit_event_generated=False,
            )
            self._hit_result = HitResultStub(
                attack_hit=False,
                event_is_hit_event=False,
            )
            return

        if self.has_source_change_effect:
            damage = max(0, self.attack_power - self.total_defense)
            self._damage_result = DamageStepResultStub(
                damage_dealt=damage,
                event_generated=damage > 0,
                hit_event_generated=False,  # source changed, not a hit-event
            )
            self._hit_result = HitResultStub(
                attack_hit=False,
                event_is_hit_event=False,
            )
            return

        damage = max(0, self.attack_power - self.total_defense)
        in_damage_step = (self.current_step == "damage")
        hit_event = damage > 0 and in_damage_step

        triggered = hit_event and not self.hit_triggers_suppressed

        self._damage_result = DamageStepResultStub(
            damage_dealt=damage,
            event_generated=damage > 0,
            hit_event_generated=hit_event,
            hit_event_source="active_attack" if hit_event else "",
            total_defense=self.total_defense,
        )

        if self.life_loss_from_effect:
            self._hit_result = HitResultStub(
                attack_hit=False,
                life_loss_was_hit_event=False,
            )
        else:
            self._hit_result = HitResultStub(
                attack_hit=hit_event,
                event_is_hit_event=hit_event,
                triggered_effects_fired=triggered,
            )

    def calculate_damage_multiple_targets(self):
        """Calculate damage for multiple attack-targets."""
        try:
            from fab_engine.combat.damage_step import DamageStep
            step = DamageStep()
            result = step.calculate_damage_multiple_targets(
                attack_power=self.attack_power,
                target_a_defense=self.target_a_defense,
                target_b_defense=self.target_b_defense,
                clockwise_order=self.attack_targets_clockwise_order,
            )
            self._multi_target_result = result
        except (ImportError, AttributeError, TypeError):
            # Build from local state
            target_a_damage = max(0, self.attack_power - self.target_a_defense)
            target_b_damage = max(0, self.attack_power - self.target_b_defense)
            self._multi_target_result = MultiTargetDamageResultStub(
                target_a_damage=target_a_damage,
                target_b_damage=target_b_damage,
                processed_in_clockwise_order=True,
            )

    def begin_priority_phase(self):
        """Begin the priority phase of the Damage Step."""
        try:
            from fab_engine.combat.damage_step import DamageStep
            step = DamageStep()
            step.begin_priority_phase()
            self.turn_player_has_priority = True
        except (ImportError, AttributeError):
            self.turn_player_has_priority = True

    def evaluate_hit(self):
        """Evaluate whether the attack has hit."""
        if self._hit_result is None:
            self._build_damage_result_from_state()

    def evaluate_chain_link_hit(self):
        """Evaluate whether the chain link has hit."""
        try:
            from fab_engine.combat.chain_link import ChainLink
            chain_link = ChainLink()
            result = chain_link.evaluate_hit()
            self._chain_link_hit_result = result
        except (ImportError, AttributeError):
            # Chain link has hit if any hit-event occurred while it was active
            if self._damage_result and self._damage_result.hit_event_generated:
                self._chain_link_hit_result = ChainLinkHitResultStub(chain_link_has_hit=True)
            else:
                # Build from local state
                damage = max(0, self.attack_power - self.total_defense)
                hit = damage > 0 and self.current_step == "damage"
                self._chain_link_hit_result = ChainLinkHitResultStub(chain_link_has_hit=hit)

    def get_current_step(self):
        """Get the current game step."""
        try:
            from fab_engine.combat.combat_state import CombatState
            state = CombatState()
            step_name = state.current_step
            damage_active = getattr(state, "damage_calculation_active", False)
            return StepResultStub(step_name=step_name, damage_calculation_active=damage_active)
        except (ImportError, AttributeError):
            return StepResultStub(
                step_name=self.current_step,
                damage_calculation_active=(self.current_step == "damage"),
            )

    def get_damage_result(self):
        """Get the damage calculation result."""
        if self._damage_result is None:
            self._build_damage_result_from_state()
        return self._damage_result

    def get_multi_target_result(self):
        """Get the multi-target damage result."""
        if self._multi_target_result is None:
            self.calculate_damage_multiple_targets()
        return self._multi_target_result

    def get_priority_result(self):
        """Get the priority result."""
        return PriorityResultStub(turn_player_has_priority=self.turn_player_has_priority)

    def get_hit_result(self):
        """Get the hit determination result."""
        if self._hit_result is None:
            self._build_damage_result_from_state()
        return self._hit_result

    def get_chain_link_hit_result(self):
        """Get the chain link hit result."""
        if self._chain_link_hit_result is None:
            self.evaluate_chain_link_hit()
        return self._chain_link_hit_result
