"""
Step definitions for Section 6.2: Continuous Effects
Reference: Flesh and Blood Comprehensive Rules Section 6.2

This module implements behavioral tests for continuous effects — effects that
modify the state/properties of objects or the rules of the game, and persist
for a specified duration or while their source ability is functional.

Engine Features Needed for Section 6.2:
- [ ] create_layer_continuous_effect(modifier, duration) -> ContinuousEffect (Rule 6.2.2)
- [ ] create_static_continuous_effect(modifier, source_ability) -> ContinuousEffect (Rule 6.2.3)
- [ ] continuous_effect.is_active() -> bool (Rule 6.2.1)
- [ ] continuous_effect.duration: fixed at generation time, does not change (Rule 6.2.2a)
- [ ] continuous_effect.end_at_end_of_turn() for no-explicit-duration effects (Rule 6.2.2a)
- [ ] continuous_effect.variable_values: fixed at generation or first application (Rule 6.2.2b)
- [ ] continuous_effect.continues_applying_after_property_change() -> bool (Rule 6.2.2c)
- [ ] continuous_effect.evaluate_generation_condition_once() -> bool (Rule 6.2.2d)
- [ ] continuous_effect.evaluate_application_condition_continuously() -> bool (Rule 6.2.2d)
- [ ] static_effect.start_when_ability_functional() (Rule 6.2.3a)
- [ ] static_effect.end_when_ability_nonfunctional() (Rule 6.2.3a)
- [ ] static_effect.variable_values: updated dynamically from game state (Rule 6.2.3b)
- [ ] static_effect.stops_applying_when_properties_change() -> bool (Rule 6.2.3c)
- [ ] conditional_static_effect.condition_evaluated_at_all_times() (Rule 6.2.3d)
- [ ] continuous_effect.apply_to_next_qualifying_object() (Rule 6.2.4)
- [ ] continuous_effect.first_application_is_event() -> bool (Rule 6.2.5)
- [ ] ContinuousEffectStagingSystem.apply_in_staging_order(effects, target) (Rule 6.2.5a)

Current status: Tests written, Engine pending
"""

import pytest
from pytest_bdd import scenario, given, when, then, parsers


# ===== Scenarios =====


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A continuous effect modifies the properties of an object",
)
def test_continuous_effect_modifies_object_properties():
    """Rule 6.2.1: A continuous effect modifies the properties of an object."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A continuous effect modifies the rules of the game",
)
def test_continuous_effect_modifies_game_rules():
    """Rule 6.2.1: A continuous effect can modify the rules of the game."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect is generated when a layer resolves",
)
def test_layer_continuous_effect_generated_on_resolution():
    """Rule 6.2.2: A layer-continuous effect is generated by the resolution of a layer."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect starts immediately upon generation",
)
def test_layer_continuous_effect_starts_immediately():
    """Rule 6.2.2a: A layer-continuous effect starts as soon as it is generated."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "The duration of a layer-continuous effect is fixed at generation time",
)
def test_layer_continuous_effect_duration_fixed_at_generation():
    """Rule 6.2.2a: Duration is fixed at generation; does not update when controller changes."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect with no explicit duration ends at end of turn",
)
def test_layer_continuous_effect_no_duration_ends_at_turn_end():
    """Rule 6.2.2a: If no duration is specified, the effect ends at end of turn."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A condition-dependent layer-continuous effect ends when its condition is no longer met",
)
def test_condition_dependent_effect_ends_when_condition_not_met():
    """Rule 6.2.2a: Condition-dependent effects end when the condition is no longer met."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect with variable X fixes X at generation time",
)
def test_layer_continuous_effect_x_fixed_at_generation():
    """Rule 6.2.2b: Variable X is fixed at generation time and does not update."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "Variable X in a layer-continuous effect is fixed when the effect first applies to a new object",
)
def test_layer_continuous_effect_x_fixed_at_first_application():
    """Rule 6.2.2b: Variable X is fixed when the effect first applies to an object not yet existing."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect continues to apply after the target's properties change",
)
def test_layer_continuous_effect_persists_after_property_change():
    """Rule 6.2.2c: Once applied to an object, the effect persists even if properties change."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect's generation condition is evaluated only once",
)
def test_layer_continuous_effect_generation_condition_evaluated_once():
    """Rule 6.2.2d: Generation condition evaluated only once at generation time."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A layer-continuous effect's application condition is checked continuously",
)
def test_layer_continuous_effect_application_condition_checked_continuously():
    """Rule 6.2.2d: Application condition is still checked continuously."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A static-continuous effect is generated by a static ability",
)
def test_static_continuous_effect_from_static_ability():
    """Rule 6.2.3: A static-continuous effect is generated by a static ability."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A static-continuous effect starts when its source static ability becomes functional",
)
def test_static_continuous_effect_starts_with_ability():
    """Rule 6.2.3a: Static-continuous effect starts when the static ability becomes functional."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A static-continuous effect ends when its source static ability becomes non-functional",
)
def test_static_continuous_effect_ends_when_ability_nonfunctional():
    """Rule 6.2.3a: Static-continuous effect ends when the static ability becomes non-functional."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "Variable values in a static-continuous effect update when game state changes",
)
def test_static_continuous_effect_variable_values_update():
    """Rule 6.2.3b: Variable values in static-continuous effects update with game state."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A static-continuous effect stops applying when the target loses qualifying properties",
)
def test_static_continuous_effect_stops_when_properties_change():
    """Rule 6.2.3c: Static-continuous effect stops applying when object loses qualifying properties."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A conditional static-continuous effect activates when its condition becomes true",
)
def test_conditional_static_effect_activates_when_condition_met():
    """Rule 6.2.3d: Conditional static-continuous effect activates when condition becomes true."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A conditional static-continuous effect deactivates when its condition becomes false",
)
def test_conditional_static_effect_deactivates_when_condition_not_met():
    """Rule 6.2.3d: Conditional static-continuous effect ceases when condition is no longer met."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A continuous effect that targets a future object applies to the next qualifying object",
)
def test_continuous_effect_applies_to_next_qualifying_object():
    """Rule 6.2.4: A continuous effect targeting a future object applies to the next qualifying one."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A continuous effect for a future object does not apply to objects that already exist",
)
def test_continuous_effect_does_not_apply_to_existing_objects():
    """Rule 6.2.4: Effect targeting a future object does not apply to pre-existing objects."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "The first application of a continuous effect to an object is an event",
)
def test_first_application_of_continuous_effect_is_event():
    """Rule 6.2.5: First application of a continuous effect to an object is an event."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "A change in how a continuous effect modifies an object is treated as an event",
)
def test_change_in_continuous_effect_modification_is_event():
    """Rule 6.2.5: A change in how a continuous effect modifies an object is also an event."""
    pass


@scenario(
    "../features/section_6_2_continuous_effects.feature",
    "Two continuous effects applying to an object simultaneously are applied in staging order",
)
def test_simultaneous_effects_applied_in_staging_order():
    """Rule 6.2.5a: Simultaneous effects are applied in the order determined by staging."""
    pass


# ===== Step Definitions =====


@given("a game is in progress")
def game_in_progress(game_state):
    """Set up a basic game state."""
    assert game_state is not None


@given("a player has a continuous effect that grants \"+2{p}\" to an attack")
def player_has_power_continuous_effect(game_state):
    """Rule 6.2.1: Create a continuous effect that grants +2 power."""
    effect = game_state.create_continuous_effect(modifier="+2{p}", target="attack")
    game_state.active_continuous_effect = effect
    game_state.attack_card = game_state.create_card(name="Test Attack", card_type="attack action")


@when("the effect is active")
def effect_is_active(game_state):
    """Rule 6.2.1: Verify the effect is active."""
    game_state.effect_active = game_state.active_continuous_effect.is_active()


@then("the attack's power property is modified by the continuous effect")
def attack_power_is_modified(game_state):
    """Rule 6.2.1: The attack's power is modified by the continuous effect."""
    result = game_state.apply_continuous_effect(game_state.active_continuous_effect, game_state.attack_card)
    assert result.modifier_applied


@then("the modification persists until the effect's duration expires")
def modification_persists_until_duration_expires(game_state):
    """Rule 6.2.1: The modification is ongoing for the duration."""
    assert game_state.active_continuous_effect.has_duration or game_state.active_continuous_effect.is_active()


@given("a continuous effect that prevents pitching cards is active")
def rule_modifying_continuous_effect_active(game_state):
    """Rule 6.2.1: A continuous effect that prevents pitching (a rule modification)."""
    effect = game_state.create_continuous_effect(modifier="prevent_pitch", target="rules")
    game_state.active_continuous_effect = effect


@when("a player attempts to pitch a card")
def player_attempts_to_pitch(game_state):
    """Rule 6.2.1: A player attempts to pitch a card while a rule-modifying effect is active."""
    card = game_state.create_card(name="Test Card")
    game_state.pitch_result = game_state.attempt_pitch_under_continuous_effect(
        game_state.player, card, game_state.active_continuous_effect
    )


@then("the pitch action is prevented by the continuous rule modification")
def pitch_is_prevented(game_state):
    """Rule 6.2.1: The rule-modifying continuous effect prevents pitching."""
    assert not game_state.pitch_result.success


@given("a player resolves a card with a lasting power bonus effect")
def player_resolves_card_with_lasting_effect(game_state):
    """Rule 6.2.2: A layer resolves, creating a lasting power bonus."""
    game_state.source_card = game_state.create_card(name="Power Boost Card")
    game_state.resolved_layer = game_state.create_layer_with_continuous_effect(
        game_state.source_card, modifier="+3{p}", duration="end_of_turn"
    )


@when("the layer resolves")
def layer_resolves(game_state):
    """Rule 6.2.2: Resolve the layer."""
    game_state.layer_resolution_result = game_state.resolve_layer(game_state.resolved_layer)


@then("a layer-continuous effect is created in the game state")
def layer_continuous_effect_is_created(game_state):
    """Rule 6.2.2: A layer-continuous effect is created when a layer resolves."""
    assert game_state.layer_resolution_result.continuous_effect_created


@then("the effect modifies the targeted object's properties")
def effect_modifies_target(game_state):
    """Rule 6.2.2: The generated continuous effect modifies the targeted object."""
    assert game_state.layer_resolution_result.effect.modifier == "+3{p}"


@given("a player plays a card that creates a layer-continuous effect")
def player_plays_card_creating_continuous_effect(game_state):
    """Rule 6.2.2a: A card is played that creates a layer-continuous effect."""
    game_state.source_card = game_state.create_card(name="Stasis Cell Style Card")
    game_state.layer = game_state.create_layer_with_continuous_effect(
        game_state.source_card, modifier="disable_activated_abilities", duration="until_end_of_next_turn"
    )


@when("the layer resolves and the effect is generated")
def layer_resolves_and_effect_generated(game_state):
    """Rule 6.2.2a: The layer resolves and generates the continuous effect."""
    game_state.generation_result = game_state.resolve_layer_and_generate_effect(game_state.layer)


@then("the continuous effect is active immediately")
def continuous_effect_active_immediately(game_state):
    """Rule 6.2.2a: The effect starts as soon as it is generated."""
    assert game_state.generation_result.effect_is_active_immediately


@then("the effect modifies the targeted object right away")
def effect_modifies_immediately(game_state):
    """Rule 6.2.2a: The effect applies immediately upon generation."""
    assert game_state.generation_result.modification_applied


@given(parsers.parse('a player generates a layer-continuous effect with duration "{duration}"'))
def player_generates_effect_with_duration(game_state, duration):
    """Rule 6.2.2a: A layer-continuous effect is generated with a specific duration."""
    game_state.original_controller_id = 0
    game_state.effect = game_state.create_layer_continuous_effect(
        modifier="disable_activated_abilities",
        duration=duration,
        controller_id=game_state.original_controller_id
    )
    game_state.original_duration = game_state.effect.duration


@when("the controller of the affected object changes")
def controller_of_object_changes(game_state):
    """Rule 6.2.2a: The controller of the object the effect applies to changes."""
    new_controller_id = 1
    game_state.change_object_controller_result = game_state.change_object_controller(
        game_state.effect.target_object, new_controller_id
    )


@then(parsers.parse('the duration of the effect remains "{expected_duration}"'))
def duration_remains_fixed(game_state, expected_duration):
    """Rule 6.2.2a: The duration does not change when the controller changes."""
    assert game_state.effect.duration == game_state.original_duration


@then("the duration does not track the new controller's turn")
def duration_does_not_track_new_controller(game_state):
    """Rule 6.2.2a: Duration is fixed at generation and does not update."""
    assert not game_state.effect.tracks_controller_dynamically


@given("a player generates a layer-continuous effect with no explicit duration or condition")
def player_generates_effect_with_no_duration(game_state):
    """Rule 6.2.2a: An effect is generated with no explicit duration or condition."""
    game_state.effect = game_state.create_layer_continuous_effect(
        modifier="+1_arcane_plus_1",
        duration=None,  # No explicit duration
        condition=None
    )


@when("the current turn ends")
def current_turn_ends(game_state):
    """Rule 6.2.2a: The current turn ends."""
    game_state.turn_end_result = game_state.end_current_turn()


@then("the layer-continuous effect is no longer active")
def layer_continuous_effect_is_not_active(game_state):
    """Rule 6.2.2a: The effect ends at the end of the turn it was generated."""
    assert not game_state.effect.is_active()


@then("the effect no longer modifies any objects")
def effect_does_not_modify_objects(game_state):
    """Rule 6.2.2a: After expiry, the effect has no further influence."""
    assert not game_state.effect.is_modifying_any_object()


@given("a player has a permanent with a condition-dependent continuous effect in the arena")
def permanent_with_condition_dependent_effect_in_arena(game_state):
    """Rule 6.2.2a: A permanent generating a condition-dependent continuous effect is in the arena."""
    game_state.permanent = game_state.create_card(name="Chains of Eminence Style Card", card_type="equipment")
    game_state.play_card_to_arena(game_state.permanent)
    game_state.effect = game_state.create_condition_dependent_continuous_effect(
        modifier="prevent_play_pitch_defend",
        condition=f"while permanent {game_state.permanent.id} is in arena"
    )


@when("the permanent leaves the arena")
def permanent_leaves_arena(game_state):
    """Rule 6.2.2a: The permanent is removed from the arena."""
    game_state.remove_from_arena_result = game_state.remove_permanent_from_arena(game_state.permanent)


@then("the condition-dependent continuous effect ends")
def condition_dependent_effect_ends(game_state):
    """Rule 6.2.2a: The effect ends when its condition (being in the arena) is no longer met."""
    assert not game_state.effect.is_active()


@then("the effect is no longer active")
def effect_is_no_longer_active(game_state):
    """Rule 6.2.2a/6.2.3d: The effect has stopped applying."""
    assert not game_state.effect.is_active()


@given("a player generates a layer-continuous effect with a variable power bonus \"X\"")
def player_generates_effect_with_variable_x(game_state):
    """Rule 6.2.2b: A layer-continuous effect with variable X is generated."""
    game_state.initial_x_value = 3
    game_state.effect = game_state.create_layer_continuous_effect_with_variable(
        modifier="+X{p}",
        variable_name="X",
        variable_value=game_state.initial_x_value
    )


@given(parsers.parse('the value of X is "{x_value}" when the effect is generated'))
def value_of_x_at_generation(game_state, x_value):
    """Rule 6.2.2b: X is set to the given value at generation."""
    assert game_state.effect.get_variable_value("X") == int(x_value)


@when(parsers.parse('the game state changes so that X would be "{new_x}"'))
def game_state_x_changes(game_state, new_x):
    """Rule 6.2.2b: The underlying game state that determined X changes."""
    game_state.new_x_value = int(new_x)
    game_state.simulate_game_state_change_affecting_variable("X", game_state.new_x_value)


@then(parsers.parse('the continuous effect still grants "+{expected_value}{{p}}" based on the original X value'))
def effect_uses_original_x(game_state, expected_value):
    """Rule 6.2.2b: The effect uses the X value fixed at generation, not the updated value."""
    assert game_state.effect.get_variable_value("X") == int(expected_value)


@then("the effect does not update to use the new value of X")
def effect_does_not_update_x(game_state):
    """Rule 6.2.2b: For layer-continuous effects, X is fixed and does not update."""
    assert game_state.effect.get_variable_value("X") != game_state.new_x_value


@given("a player generates a layer-continuous effect that applies to the next attack played with \"+X{p} where X is its base power\"")
def player_generates_future_object_effect_with_variable(game_state):
    """Rule 6.2.2b: Effect applies to a future object; X determined at first application."""
    game_state.effect = game_state.create_layer_continuous_effect_for_future_object(
        modifier="+X{p}_where_X_is_base_power",
        target_spec="next attack played this turn"
    )


@given(parsers.parse('the next attack played has base power "{base_power}"'))
def next_attack_has_base_power(game_state, base_power):
    """Rule 6.2.2b: The next attack has a specific base power."""
    game_state.future_attack = game_state.create_card(
        name="Future Attack", card_type="attack action", power=int(base_power)
    )


@when("the layer-continuous effect first applies to that attack")
def effect_first_applies_to_attack(game_state):
    """Rule 6.2.2b: The effect applies to the attack when it is played."""
    game_state.application_result = game_state.apply_future_object_effect(
        game_state.effect, game_state.future_attack
    )


@then(parsers.parse('the effect grants "+{expected_bonus}{{p}}" based on the attack\'s base power at time of application'))
def effect_grants_correct_bonus(game_state, expected_bonus):
    """Rule 6.2.2b: X is the base power of the attack at first application."""
    assert game_state.application_result.power_bonus == int(expected_bonus)


@then("the bonus does not change if the attack's power changes later")
def bonus_does_not_change_after_power_changes(game_state):
    """Rule 6.2.2b: X is fixed at first application and does not change thereafter."""
    assert game_state.application_result.x_is_fixed


@given("a player generates a layer-continuous effect targeting \"the next dagger attack\" with \"+4{p}\"")
def player_generates_dagger_attack_effect(game_state):
    """Rule 6.2.2c: An effect targets the next dagger attack with +4 power."""
    game_state.effect = game_state.create_layer_continuous_effect_for_future_object(
        modifier="+4{p}",
        target_spec="next dagger attack this turn"
    )


@given("the effect starts to apply to a card that is a dagger attack")
def effect_starts_applying_to_dagger_attack(game_state):
    """Rule 6.2.2c: The effect begins applying to a dagger attack card."""
    game_state.dagger_attack = game_state.create_card(
        name="Kiss of Death Style Card", card_type="attack action", subtype="dagger"
    )
    game_state.application_result_2c = game_state.apply_future_object_effect(
        game_state.effect, game_state.dagger_attack
    )
    assert game_state.application_result_2c.applied


@when("the card's type is changed to \"non-dagger\" by another effect")
def card_type_changed_to_non_dagger(game_state):
    """Rule 6.2.2c: Another effect changes the card's type to remove the dagger subtype."""
    game_state.type_change_result = game_state.change_card_subtype(
        game_state.dagger_attack, remove_subtype="dagger"
    )


@then("the \"+4{p}\" layer-continuous effect still applies to the card")
def effect_still_applies_after_type_change(game_state):
    """Rule 6.2.2c: The effect continues applying even though properties changed."""
    assert game_state.effect.is_currently_applying_to(game_state.dagger_attack)


@then("the power bonus remains active despite the type change")
def power_bonus_remains_active(game_state):
    """Rule 6.2.2c: The +4 power bonus from the effect remains active."""
    effective_bonus = game_state.get_continuous_effect_bonus(game_state.effect, game_state.dagger_attack)
    assert effective_bonus == 4


@given("a player has a card with a conditional continuous effect \"if you have more life than your opponent, your next attack gets +2{p}\"")
def player_has_conditional_continuous_effect_card(game_state):
    """Rule 6.2.2d: A card with a generation-conditional continuous effect."""
    game_state.source_card = game_state.create_card(name="Conditional Boost Card")
    game_state.layer = game_state.create_layer_with_conditional_continuous_effect(
        game_state.source_card,
        generation_condition="player_life > opponent_life",
        modifier="+2{p}",
        target_spec="next attack this turn"
    )


@given("the condition is true when the layer resolves")
def condition_is_true_at_resolution(game_state):
    """Rule 6.2.2d: The generation condition is true at the time of layer resolution."""
    game_state.player_life = 20
    game_state.opponent_life = 10
    game_state.condition_met_at_generation = True


@when("the layer resolves and the effect is generated")
def layer_resolves_and_effect_generated_2d(game_state):
    """Rule 6.2.2d: Layer resolves; condition was met, so effect is generated."""
    game_state.generation_result_2d = game_state.resolve_conditional_layer(
        game_state.layer,
        generation_condition_result=game_state.condition_met_at_generation
    )


@then("the effect is generated because the condition was met at generation time")
def effect_is_generated_condition_met(game_state):
    """Rule 6.2.2d: The effect is generated because condition was true at generation."""
    assert game_state.generation_result_2d.effect_generated


@then("if the player's life later drops below the opponent's life, the effect remains generated")
def effect_remains_after_condition_changes(game_state):
    """Rule 6.2.2d: Generation condition evaluated once; already-generated effects persist."""
    game_state.player_life = 5  # Now below opponent
    game_state.opponent_life = 10
    # The effect should still be generated (not retroactively un-generated)
    assert game_state.generation_result_2d.effect_generated
    assert game_state.generation_result_2d.effect.is_active()


@given("a layer-continuous effect that applies conditionally based on an ongoing game state property is active")
def layer_continuous_effect_with_application_condition_active(game_state):
    """Rule 6.2.2d: A layer-continuous effect with application condition is active."""
    game_state.effect = game_state.create_layer_continuous_effect_with_application_condition(
        modifier="+3{p}",
        application_condition="target_has_type_dagger"
    )
    game_state.target_card = game_state.create_card(
        name="Dagger Card", card_type="attack action", subtype="dagger"
    )
    game_state.effect_applied = True  # Currently applying


@when("the ongoing condition becomes false")
def ongoing_condition_becomes_false(game_state):
    """Rule 6.2.2d: The application condition becomes false."""
    game_state.change_card_subtype(game_state.target_card, remove_subtype="dagger")
    game_state.application_condition_false = True


@then("the effect no longer applies to objects until the condition becomes true again")
def effect_no_longer_applies(game_state):
    """Rule 6.2.2d: The application condition is checked continuously; stops when false."""
    # The effect checks continuously and stops applying when condition is false
    assert not game_state.effect.currently_applies_to(
        game_state.target_card, check_application_condition=True
    )


@given("a permanent with a static ability granting \"+1{p} to all your attacks\" is in the arena")
def permanent_with_static_ability_in_arena(game_state):
    """Rule 6.2.3: A permanent with a static ability generating a continuous effect."""
    game_state.permanent = game_state.create_card(name="Power Aura Permanent", card_type="equipment")
    game_state.static_ability = game_state.create_static_ability(
        source=game_state.permanent, modifier="+1{p}", target_spec="all attacks you control"
    )
    game_state.play_card_to_arena(game_state.permanent)
    game_state.static_effect = game_state.get_static_continuous_effect(game_state.static_ability)


@when("an attack card is played by the controlling player")
def attack_card_played_by_controlling_player(game_state):
    """Rule 6.2.3: The controller plays an attack card."""
    game_state.attack = game_state.create_card(name="Attack Card", card_type="attack action")
    game_state.play_result = game_state.player.play_card(game_state.attack)


@then("the static-continuous effect applies the \"+1{p}\" bonus to the attack")
def static_effect_applies_bonus(game_state):
    """Rule 6.2.3: The static-continuous effect modifies the attack."""
    bonus = game_state.get_continuous_effect_bonus(game_state.static_effect, game_state.attack)
    assert bonus == 1


@then("the effect has no specified duration")
def static_effect_has_no_duration(game_state):
    """Rule 6.2.3: Static-continuous effects have no specified duration."""
    assert game_state.static_effect.duration is None


@given("a permanent with a static ability enters the arena")
def permanent_with_static_ability_enters_arena(game_state):
    """Rule 6.2.3a: A permanent enters the arena."""
    game_state.permanent = game_state.create_card(name="Static Aura Permanent", card_type="equipment")
    game_state.static_ability = game_state.create_static_ability(
        source=game_state.permanent, modifier="+2{p}", target_spec="all attacks you control"
    )


@when("the permanent enters the arena and its static ability becomes functional")
def permanent_enters_arena_ability_becomes_functional(game_state):
    """Rule 6.2.3a: The permanent enters the arena, making the static ability functional."""
    game_state.arena_entry_result = game_state.play_card_to_arena(game_state.permanent)
    game_state.static_effect = game_state.check_static_ability_functional(game_state.static_ability)


@then("the static-continuous effect is immediately active")
def static_effect_immediately_active(game_state):
    """Rule 6.2.3a: Effect is active as soon as the ability becomes functional."""
    assert game_state.static_effect.is_active()


@then("it applies to qualifying objects")
def static_effect_applies_to_qualifying_objects(game_state):
    """Rule 6.2.3a: The effect applies to objects meeting the target specification."""
    qualifying_attack = game_state.create_card(name="Qualifying Attack", card_type="attack action")
    assert game_state.static_effect.would_apply_to(qualifying_attack)


@given("a permanent with a static ability is in the arena generating a continuous effect")
def permanent_generating_static_effect_in_arena(game_state):
    """Rule 6.2.3a: A permanent is in the arena with an active static ability."""
    game_state.permanent = game_state.create_card(name="Active Aura Permanent", card_type="equipment")
    game_state.static_ability = game_state.create_static_ability(
        source=game_state.permanent, modifier="+1{p}", target_spec="all attacks you control"
    )
    game_state.play_card_to_arena(game_state.permanent)
    game_state.static_effect = game_state.get_static_continuous_effect(game_state.static_ability)
    assert game_state.static_effect.is_active()


@when("the permanent leaves the arena and the static ability becomes non-functional")
def permanent_leaves_arena_ability_becomes_nonfunctional(game_state):
    """Rule 6.2.3a: The permanent leaves the arena, making the static ability non-functional."""
    game_state.remove_permanent_from_arena(game_state.permanent)
    game_state.ability_is_now_nonfunctional = not game_state.check_ability_functional(
        game_state.static_ability
    )


@then("the static-continuous effect is no longer active")
def static_effect_no_longer_active(game_state):
    """Rule 6.2.3a: The effect ends when the static ability becomes non-functional."""
    assert not game_state.static_effect.is_active()


@then("objects previously modified by the effect lose the modification")
def objects_lose_modification(game_state):
    """Rule 6.2.3a: Objects previously modified no longer receive the bonus."""
    test_attack = game_state.create_card(name="Test Attack", card_type="attack action")
    bonus = game_state.get_continuous_effect_bonus(game_state.static_effect, test_attack)
    assert bonus == 0


@given("a static-continuous effect grants \"+X{p}\" where X is the number of cards in hand")
def static_effect_with_hand_count_variable(game_state):
    """Rule 6.2.3b: A static-continuous effect with X = cards in hand."""
    game_state.static_effect = game_state.create_static_continuous_effect_with_dynamic_variable(
        modifier="+X{p}",
        variable_source="cards_in_hand"
    )


@given(parsers.parse('the player has "{card_count}" cards in hand'))
def player_has_cards_in_hand(game_state, card_count):
    """Rule 6.2.3b: Set the player's hand size."""
    game_state.set_player_hand_size(game_state.player, int(card_count))


@when(parsers.parse('the player draws a card and now has "{new_count}" cards in hand'))
def player_draws_card_new_count(game_state, new_count):
    """Rule 6.2.3b: The player draws a card, increasing their hand size."""
    game_state.draw_card_for_player(game_state.player)
    game_state.new_hand_count = int(new_count)


@then(parsers.parse('the static-continuous effect now grants "+{expected_bonus}{{p}}"'))
def static_effect_updated_bonus(game_state, expected_bonus):
    """Rule 6.2.3b: The variable X updates to reflect the current game state."""
    current_x = game_state.static_effect.get_variable_value("X")
    assert current_x == int(expected_bonus)


@then("the variable value has updated to reflect the current game state")
def variable_has_updated(game_state):
    """Rule 6.2.3b: Static-continuous effect variables update dynamically."""
    current_x = game_state.static_effect.get_variable_value("X")
    assert current_x == game_state.new_hand_count


@given("a static-continuous effect applies to all \"Illusionist attacks\" granting go again")
def static_effect_applies_to_illusionist_attacks(game_state):
    """Rule 6.2.3c: A static-continuous effect applies to Illusionist attacks."""
    game_state.static_effect = game_state.create_static_continuous_effect_by_type(
        modifier="go_again",
        target_type="Illusionist attack"
    )


@given("a card is an \"Illusionist attack\" currently benefiting from the effect")
def card_is_illusionist_attack_benefiting(game_state):
    """Rule 6.2.3c: A card qualifies as an Illusionist attack."""
    game_state.illusionist_attack = game_state.create_card(
        name="Illusionist Attack Card", card_type="attack action", subtype="Illusionist"
    )
    assert game_state.static_effect.currently_applies_to(game_state.illusionist_attack, check_application_condition=False)


@when("the card's type changes so it is no longer an \"Illusionist attack\"")
def card_type_changes_to_non_illusionist(game_state):
    """Rule 6.2.3c: The card's type changes, removing Illusionist subtype."""
    game_state.change_card_subtype(game_state.illusionist_attack, remove_subtype="Illusionist")


@then("the static-continuous effect no longer applies to that card")
def static_effect_no_longer_applies(game_state):
    """Rule 6.2.3c: The static effect does not apply when properties no longer qualify."""
    assert not game_state.static_effect.currently_applies_to(
        game_state.illusionist_attack, check_application_condition=True
    )


@then("the card no longer benefits from go again")
def card_no_longer_has_go_again(game_state):
    """Rule 6.2.3c: The go again keyword is removed when the effect stops applying."""
    assert not game_state.get_effective_keyword(game_state.illusionist_attack, "go_again")


@given("a permanent has a conditional static ability \"if there is a yellow card in pitch zone, Illusionist attacks have go again\"")
def permanent_has_conditional_static_ability(game_state):
    """Rule 6.2.3d: A permanent has a conditional static ability (Luminaris-style)."""
    game_state.luminaris_permanent = game_state.create_card(name="Luminaris Style Permanent", card_type="equipment")
    game_state.play_card_to_arena(game_state.luminaris_permanent)
    game_state.conditional_static_ability = game_state.create_conditional_static_ability(
        source=game_state.luminaris_permanent,
        condition="yellow_card_in_pitch_zone",
        modifier="go_again",
        target_spec="Illusionist attacks you control"
    )
    game_state.conditional_static_effect = game_state.get_conditional_static_effect(
        game_state.conditional_static_ability
    )


@given("the player's pitch zone has no yellow cards")
def pitch_zone_has_no_yellow_cards(game_state):
    """Rule 6.2.3d: The condition (yellow card in pitch zone) is not met."""
    game_state.clear_pitch_zone(game_state.player)
    # Condition is currently false
    assert not game_state.conditional_static_effect.is_active()


@when("the player pitches a yellow card to the pitch zone")
def player_pitches_yellow_card(game_state):
    """Rule 6.2.3d: A yellow card is pitched, satisfying the condition."""
    yellow_card = game_state.create_card(name="Yellow Card", pitch=2)
    game_state.pitch_yellow_card(game_state.player, yellow_card)


@then("the conditional static-continuous effect becomes active")
def conditional_static_effect_becomes_active(game_state):
    """Rule 6.2.3d: The condition is now met; the effect becomes active."""
    assert game_state.conditional_static_effect.is_active()


@then("Illusionist attacks controlled by that player now have go again")
def illusionist_attacks_have_go_again(game_state):
    """Rule 6.2.3d: Illusionist attacks benefit from the go again effect."""
    illusionist_attack = game_state.create_card(
        name="Test Illusionist Attack", card_type="attack action", subtype="Illusionist"
    )
    assert game_state.get_effective_keyword(illusionist_attack, "go_again")


@given("a conditional static-continuous effect is currently active because its condition is met")
def conditional_static_effect_currently_active(game_state):
    """Rule 6.2.3d: The conditional static-continuous effect is currently active."""
    game_state.permanent = game_state.create_card(name="Conditional Permanent", card_type="equipment")
    game_state.play_card_to_arena(game_state.permanent)
    yellow_card = game_state.create_card(name="Yellow Card In Pitch", pitch=2)
    game_state.pitch_yellow_card(game_state.player, yellow_card)
    game_state.conditional_static_ability = game_state.create_conditional_static_ability(
        source=game_state.permanent,
        condition="yellow_card_in_pitch_zone",
        modifier="go_again",
        target_spec="Illusionist attacks you control"
    )
    game_state.conditional_static_effect = game_state.get_conditional_static_effect(
        game_state.conditional_static_ability
    )
    assert game_state.conditional_static_effect.is_active()


@when("the condition becomes false")
def condition_becomes_false(game_state):
    """Rule 6.2.3d: The condition is no longer met."""
    game_state.clear_pitch_zone(game_state.player)


@then("the conditional static-continuous effect ceases to exist")
def conditional_static_effect_ceases(game_state):
    """Rule 6.2.3d: The effect ceases when the condition is no longer met."""
    assert not game_state.conditional_static_effect.is_active()


@then("the modification it applied is removed from all affected objects")
def modification_removed_from_objects(game_state):
    """Rule 6.2.3d: Objects no longer receive the modification when the effect ceases."""
    illusionist_attack = game_state.create_card(
        name="Test Illusionist Attack 2", card_type="attack action", subtype="Illusionist"
    )
    assert not game_state.get_effective_keyword(illusionist_attack, "go_again")


@given("a player generates a continuous effect \"the next attack action card you play this turn gets +3{p}\"")
def player_generates_future_attack_effect(game_state):
    """Rule 6.2.4: An effect targets the next attack action card played."""
    game_state.future_effect = game_state.create_layer_continuous_effect_for_future_object(
        modifier="+3{p}",
        target_spec="next attack action card played this turn"
    )


@when("the player plays an attack action card")
def player_plays_attack_action_card(game_state):
    """Rule 6.2.4: The player plays an attack action card."""
    game_state.new_attack = game_state.create_card(name="New Attack", card_type="attack action")
    game_state.future_effect_application = game_state.apply_future_object_effect(
        game_state.future_effect, game_state.new_attack
    )


@then("the continuous effect applies its \"+3{p}\" bonus to that attack")
def future_effect_applies_to_new_attack(game_state):
    """Rule 6.2.4: The effect applies to the first qualifying object encountered."""
    assert game_state.future_effect_application.applied
    assert game_state.future_effect_application.power_bonus == 3


@then("the effect is consumed and does not apply to subsequent attacks")
def effect_consumed_after_first_application(game_state):
    """Rule 6.2.4: Once applied to the first qualifying object, the effect is consumed."""
    second_attack = game_state.create_card(name="Second Attack", card_type="attack action")
    second_application = game_state.apply_future_object_effect(game_state.future_effect, second_attack)
    assert not second_application.applied  # Already consumed


@given("an attack action card is already on the combat chain")
def attack_already_on_combat_chain(game_state):
    """Rule 6.2.4: An existing attack action card is already on the combat chain."""
    game_state.existing_attack = game_state.create_card(name="Existing Attack", card_type="attack action")
    game_state.put_on_combat_chain(game_state.existing_attack)


@given("a player generates a continuous effect \"the next attack action card you play this turn gets +3{p}\"")
def player_generates_next_attack_effect_with_existing_attack(game_state):
    """Rule 6.2.4: Effect generated after an attack is already on the chain."""
    game_state.future_effect = game_state.create_layer_continuous_effect_for_future_object(
        modifier="+3{p}",
        target_spec="next attack action card played this turn"
    )


@when("the player does not play another attack action card")
def player_does_not_play_another_attack(game_state):
    """Rule 6.2.4: No additional attack action card is played."""
    game_state.no_additional_attack_played = True


@then("the existing attack action card on the combat chain is not affected")
def existing_attack_not_affected(game_state):
    """Rule 6.2.4: Pre-existing objects are not affected by the future object effect."""
    bonus = game_state.get_continuous_effect_bonus(game_state.future_effect, game_state.existing_attack)
    assert bonus == 0


@then("the effect waits for a new qualifying object")
def effect_waits_for_qualifying_object(game_state):
    """Rule 6.2.4: The effect remains pending, waiting for a future qualifying object."""
    assert game_state.future_effect.is_waiting_for_qualifying_object()


@given("a continuous effect is waiting to apply to the next qualifying attack")
def continuous_effect_waiting_for_attack(game_state):
    """Rule 6.2.5: A continuous effect is pending, waiting for a qualifying attack."""
    game_state.pending_effect = game_state.create_layer_continuous_effect_for_future_object(
        modifier="+2{p}",
        target_spec="next attack played this turn"
    )


@when("the continuous effect first applies to an attack")
def continuous_effect_first_applies_to_attack(game_state):
    """Rule 6.2.5: The effect first applies to an attack."""
    qualifying_attack = game_state.create_card(name="Qualifying Attack", card_type="attack action")
    game_state.first_application_event = game_state.apply_future_object_effect_as_event(
        game_state.pending_effect, qualifying_attack
    )


@then("this application is processed as an event in the game")
def first_application_is_event(game_state):
    """Rule 6.2.5: The first application of a continuous effect is processed as an event."""
    assert game_state.first_application_event.is_event


@then("the event can trigger triggered effects and be modified by replacement effects")
def event_can_trigger_and_be_replaced(game_state):
    """Rule 6.2.5: The application event can be modified by replacement/triggered effects."""
    assert game_state.first_application_event.can_trigger_triggered_effects
    assert game_state.first_application_event.can_be_modified_by_replacement


@given("a continuous effect is currently applying \"+2{p}\" to an attack")
def continuous_effect_applying_bonus(game_state):
    """Rule 6.2.5: A continuous effect is applying a +2 power bonus."""
    game_state.attack_card = game_state.create_card(name="Active Attack", card_type="attack action")
    game_state.ongoing_effect = game_state.create_layer_continuous_effect(
        modifier="+2{p}", duration="end_of_turn"
    )
    game_state.apply_continuous_effect(game_state.ongoing_effect, game_state.attack_card)


@when("a replacement effect changes the application to \"+5{p}\" instead")
def replacement_effect_changes_application(game_state):
    """Rule 6.2.5: A replacement effect modifies how the continuous effect applies."""
    replacement = game_state.create_replacement_effect(
        replaces="apply +2{p}", with_effect="apply +5{p}"
    )
    game_state.modified_application_event = game_state.apply_replacement_to_continuous_effect(
        game_state.ongoing_effect, game_state.attack_card, replacement
    )


@then("the change in modification is processed as an event")
def change_in_modification_is_event(game_state):
    """Rule 6.2.5: A change in how a continuous effect modifies an object is also an event."""
    assert game_state.modified_application_event.is_event


@then("the attack gains \"+5{p}\" from the modified application")
def attack_gains_modified_bonus(game_state):
    """Rule 6.2.5: The attack receives the replacement effect's modified bonus."""
    assert game_state.modified_application_event.power_bonus == 5


@given("two continuous effects would both apply to an attack at the same time")
def two_simultaneous_continuous_effects(game_state):
    """Rule 6.2.5a: Two continuous effects would apply simultaneously."""
    game_state.attack_card = game_state.create_card(name="Target Attack", card_type="attack action")
    game_state.effect_a = game_state.create_layer_continuous_effect(modifier="+2{p}", duration="end_of_turn")
    game_state.effect_b = game_state.create_layer_continuous_effect(modifier="+3{p}", duration="end_of_turn")


@when("the effects are applied to the attack")
def effects_are_applied_to_attack(game_state):
    """Rule 6.2.5a: Apply both effects to the attack."""
    game_state.staging_result = game_state.apply_simultaneous_effects_in_staging_order(
        [game_state.effect_a, game_state.effect_b],
        game_state.attack_card
    )


@then("they are applied in the order determined by the staging system")
def effects_applied_in_staging_order(game_state):
    """Rule 6.2.5a: The staging system determines the order of application."""
    assert game_state.staging_result.applied_in_staging_order


@then("each application is a separate event")
def each_application_is_separate_event(game_state):
    """Rule 6.2.5a: Each effect application is a separate event."""
    assert len(game_state.staging_result.application_events) == 2


# ===== Fixtures =====


@pytest.fixture
def game_state():
    """
    Fixture providing game state for testing continuous effects.

    Uses BDDGameState which integrates with the real engine.
    Reference: Rule 6.2 Continuous Effects
    """
    from tests.bdd_helpers import BDDGameState

    state = BDDGameState()
    state.effect = None
    state.active_continuous_effect = None
    state.static_effect = None

    return state
